services:
  products:
    build: .
    container_name: products
    restart: unless-stopped
    environment:
      - SERVICE_NAME=products
      - CONSUL_ADDRESS=${CONSUL_ADDRESS}
      - VAULT_ADDRESS=${VAULT_ADDRESS}
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_DEV_ROOT_TOKEN_ID}
      - DEBUG=${DEBUG}
      - AUTOMIGRATE=${AUTOMIGRATE}
