// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/products/v1/models.proto

package products_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Barcode       string                 `protobuf:"bytes,4,opt,name=barcode,proto3" json:"barcode,omitempty"`
	CategoryId    int64                  `protobuf:"varint,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Unit          string                 `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	PurchasePrice string                 `protobuf:"bytes,7,opt,name=purchase_price,json=purchasePrice,proto3" json:"purchase_price,omitempty"`
	SellingPrice  string                 `protobuf:"bytes,8,opt,name=selling_price,json=sellingPrice,proto3" json:"selling_price,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	Sku           string                 `protobuf:"bytes,10,opt,name=sku,proto3" json:"sku,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Barcodes      []*Barcode             `protobuf:"bytes,13,rep,name=barcodes,proto3" json:"barcodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_api_products_v1_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_api_products_v1_models_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *Product) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Product) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Product) GetPurchasePrice() string {
	if x != nil {
		return x.PurchasePrice
	}
	return ""
}

func (x *Product) GetSellingPrice() string {
	if x != nil {
		return x.SellingPrice
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Product) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Product) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Product) GetBarcodes() []*Barcode {
	if x != nil {
		return x.Barcodes
	}
	return nil
}

type Barcode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Barcode) Reset() {
	*x = Barcode{}
	mi := &file_api_products_v1_models_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Barcode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Barcode) ProtoMessage() {}

func (x *Barcode) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_models_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Barcode.ProtoReflect.Descriptor instead.
func (*Barcode) Descriptor() ([]byte, []int) {
	return file_api_products_v1_models_proto_rawDescGZIP(), []int{1}
}

func (x *Barcode) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Barcode) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *Barcode) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Barcode) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Barcode) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Barcode) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type PriceHistory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ProductId     int64                  `protobuf:"varint,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	PriceType     string                 `protobuf:"bytes,4,opt,name=price_type,json=priceType,proto3" json:"price_type,omitempty"`
	OldPrice      string                 `protobuf:"bytes,5,opt,name=old_price,json=oldPrice,proto3" json:"old_price,omitempty"`
	NewPrice      string                 `protobuf:"bytes,6,opt,name=new_price,json=newPrice,proto3" json:"new_price,omitempty"`
	ChangedBy     int64                  `protobuf:"varint,7,opt,name=changed_by,json=changedBy,proto3" json:"changed_by,omitempty"`
	Reason        string                 `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	ChangedAt     string                 `protobuf:"bytes,9,opt,name=changed_at,json=changedAt,proto3" json:"changed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceHistory) Reset() {
	*x = PriceHistory{}
	mi := &file_api_products_v1_models_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceHistory) ProtoMessage() {}

func (x *PriceHistory) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_models_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceHistory.ProtoReflect.Descriptor instead.
func (*PriceHistory) Descriptor() ([]byte, []int) {
	return file_api_products_v1_models_proto_rawDescGZIP(), []int{2}
}

func (x *PriceHistory) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PriceHistory) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *PriceHistory) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *PriceHistory) GetPriceType() string {
	if x != nil {
		return x.PriceType
	}
	return ""
}

func (x *PriceHistory) GetOldPrice() string {
	if x != nil {
		return x.OldPrice
	}
	return ""
}

func (x *PriceHistory) GetNewPrice() string {
	if x != nil {
		return x.NewPrice
	}
	return ""
}

func (x *PriceHistory) GetChangedBy() int64 {
	if x != nil {
		return x.ChangedBy
	}
	return 0
}

func (x *PriceHistory) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PriceHistory) GetChangedAt() string {
	if x != nil {
		return x.ChangedAt
	}
	return ""
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      int64                  `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ParentId      int64                  `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_api_products_v1_models_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_models_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_api_products_v1_models_proto_rawDescGZIP(), []int{3}
}

func (x *Category) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetTenantId() int64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *Category) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Category) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_api_products_v1_models_proto protoreflect.FileDescriptor

const file_api_products_v1_models_proto_rawDesc = "" +
	"\n" +
	"\x1capi/products/v1/models.proto\x12\vproducts.v1\"\x89\x03\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\abarcode\x18\x04 \x01(\tR\abarcode\x12\x1f\n" +
	"\vcategory_id\x18\x05 \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04unit\x18\x06 \x01(\tR\x04unit\x12%\n" +
	"\x0epurchase_price\x18\a \x01(\tR\rpurchasePrice\x12#\n" +
	"\rselling_price\x18\b \x01(\tR\fsellingPrice\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x10\n" +
	"\x03sku\x18\n" +
	" \x01(\tR\x03sku\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\f \x01(\tR\tupdatedAt\x120\n" +
	"\bbarcodes\x18\r \x03(\v2\x14.products.v1.BarcodeR\bbarcodes\"\x9e\x01\n" +
	"\aBarcode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x03R\tproductId\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"\x89\x02\n" +
	"\fPriceHistory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\x03R\tproductId\x12\x1d\n" +
	"\n" +
	"price_type\x18\x04 \x01(\tR\tpriceType\x12\x1b\n" +
	"\told_price\x18\x05 \x01(\tR\boldPrice\x12\x1b\n" +
	"\tnew_price\x18\x06 \x01(\tR\bnewPrice\x12\x1d\n" +
	"\n" +
	"changed_by\x18\a \x01(\x03R\tchangedBy\x12\x16\n" +
	"\x06reason\x18\b \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"changed_at\x18\t \x01(\tR\tchangedAt\"\xa6\x01\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x03R\btenantId\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\x03R\bparentId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAtBFZDgitlab.calendaria.team/services/products/api/products/v1;products_v1b\x06proto3"

var (
	file_api_products_v1_models_proto_rawDescOnce sync.Once
	file_api_products_v1_models_proto_rawDescData []byte
)

func file_api_products_v1_models_proto_rawDescGZIP() []byte {
	file_api_products_v1_models_proto_rawDescOnce.Do(func() {
		file_api_products_v1_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_products_v1_models_proto_rawDesc), len(file_api_products_v1_models_proto_rawDesc)))
	})
	return file_api_products_v1_models_proto_rawDescData
}

var file_api_products_v1_models_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_products_v1_models_proto_goTypes = []any{
	(*Product)(nil),      // 0: products.v1.Product
	(*Barcode)(nil),      // 1: products.v1.Barcode
	(*PriceHistory)(nil), // 2: products.v1.PriceHistory
	(*Category)(nil),     // 3: products.v1.Category
}
var file_api_products_v1_models_proto_depIdxs = []int32{
	1, // 0: products.v1.Product.barcodes:type_name -> products.v1.Barcode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_products_v1_models_proto_init() }
func file_api_products_v1_models_proto_init() {
	if File_api_products_v1_models_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_products_v1_models_proto_rawDesc), len(file_api_products_v1_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_products_v1_models_proto_goTypes,
		DependencyIndexes: file_api_products_v1_models_proto_depIdxs,
		MessageInfos:      file_api_products_v1_models_proto_msgTypes,
	}.Build()
	File_api_products_v1_models_proto = out.File
	file_api_products_v1_models_proto_goTypes = nil
	file_api_products_v1_models_proto_depIdxs = nil
}
