// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/products/v1/products.proto

package products_v1

import (
	v1 "github.com/makesalekz/utils/api/utils/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImportFormat int32

const (
	ImportFormat_CSV  ImportFormat = 0
	ImportFormat_XLSX ImportFormat = 1
)

// Enum value maps for ImportFormat.
var (
	ImportFormat_name = map[int32]string{
		0: "CSV",
		1: "XLSX",
	}
	ImportFormat_value = map[string]int32{
		"CSV":  0,
		"XLSX": 1,
	}
)

func (x ImportFormat) Enum() *ImportFormat {
	p := new(ImportFormat)
	*p = x
	return p
}

func (x ImportFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImportFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_api_products_v1_products_proto_enumTypes[0].Descriptor()
}

func (ImportFormat) Type() protoreflect.EnumType {
	return &file_api_products_v1_products_proto_enumTypes[0]
}

func (x ImportFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImportFormat.Descriptor instead.
func (ImportFormat) EnumDescriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{0}
}

type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Barcode       string                 `protobuf:"bytes,2,opt,name=barcode,proto3" json:"barcode,omitempty"`
	CategoryId    int64                  `protobuf:"varint,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Unit          string                 `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	PurchasePrice string                 `protobuf:"bytes,5,opt,name=purchase_price,json=purchasePrice,proto3" json:"purchase_price,omitempty"`
	SellingPrice  string                 `protobuf:"bytes,6,opt,name=selling_price,json=sellingPrice,proto3" json:"selling_price,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Sku           string                 `protobuf:"bytes,8,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_api_products_v1_products_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *CreateProductRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateProductRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *CreateProductRequest) GetPurchasePrice() string {
	if x != nil {
		return x.PurchasePrice
	}
	return ""
}

func (x *CreateProductRequest) GetSellingPrice() string {
	if x != nil {
		return x.SellingPrice
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

type CreateProductReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductReply) Reset() {
	*x = CreateProductReply{}
	mi := &file_api_products_v1_products_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductReply) ProtoMessage() {}

func (x *CreateProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductReply.ProtoReflect.Descriptor instead.
func (*CreateProductReply) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductReply) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_api_products_v1_products_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{2}
}

func (x *GetProductRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetProductReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductReply) Reset() {
	*x = GetProductReply{}
	mi := &file_api_products_v1_products_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductReply) ProtoMessage() {}

func (x *GetProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductReply.ProtoReflect.Descriptor instead.
func (*GetProductReply) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductReply) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paginate      *v1.PaginateRequest    `protobuf:"bytes,1,opt,name=paginate,proto3" json:"paginate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_api_products_v1_products_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{4}
}

func (x *ListProductsRequest) GetPaginate() *v1.PaginateRequest {
	if x != nil {
		return x.Paginate
	}
	return nil
}

type ListProductsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Product             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Paginate      *v1.PaginateReply      `protobuf:"bytes,2,opt,name=paginate,proto3" json:"paginate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsReply) Reset() {
	*x = ListProductsReply{}
	mi := &file_api_products_v1_products_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsReply) ProtoMessage() {}

func (x *ListProductsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsReply.ProtoReflect.Descriptor instead.
func (*ListProductsReply) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{5}
}

func (x *ListProductsReply) GetItems() []*Product {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListProductsReply) GetPaginate() *v1.PaginateReply {
	if x != nil {
		return x.Paginate
	}
	return nil
}

type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Barcode       string                 `protobuf:"bytes,3,opt,name=barcode,proto3" json:"barcode,omitempty"`
	CategoryId    int64                  `protobuf:"varint,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Unit          string                 `protobuf:"bytes,5,opt,name=unit,proto3" json:"unit,omitempty"`
	PurchasePrice string                 `protobuf:"bytes,6,opt,name=purchase_price,json=purchasePrice,proto3" json:"purchase_price,omitempty"`
	SellingPrice  string                 `protobuf:"bytes,7,opt,name=selling_price,json=sellingPrice,proto3" json:"selling_price,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Sku           string                 `protobuf:"bytes,9,opt,name=sku,proto3" json:"sku,omitempty"`
	Reason        string                 `protobuf:"bytes,14,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_api_products_v1_products_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateProductRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

func (x *UpdateProductRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *UpdateProductRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *UpdateProductRequest) GetPurchasePrice() string {
	if x != nil {
		return x.PurchasePrice
	}
	return ""
}

func (x *UpdateProductRequest) GetSellingPrice() string {
	if x != nil {
		return x.SellingPrice
	}
	return ""
}

func (x *UpdateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *UpdateProductRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UpdateProductReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductReply) Reset() {
	*x = UpdateProductReply{}
	mi := &file_api_products_v1_products_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductReply) ProtoMessage() {}

func (x *UpdateProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductReply.ProtoReflect.Descriptor instead.
func (*UpdateProductReply) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateProductReply) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_api_products_v1_products_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteProductRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteProductReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductReply) Reset() {
	*x = DeleteProductReply{}
	mi := &file_api_products_v1_products_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductReply) ProtoMessage() {}

func (x *DeleteProductReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductReply.ProtoReflect.Descriptor instead.
func (*DeleteProductReply) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{9}
}

type AddBarcodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBarcodeRequest) Reset() {
	*x = AddBarcodeRequest{}
	mi := &file_api_products_v1_products_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBarcodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBarcodeRequest) ProtoMessage() {}

func (x *AddBarcodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBarcodeRequest.ProtoReflect.Descriptor instead.
func (*AddBarcodeRequest) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{10}
}

func (x *AddBarcodeRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *AddBarcodeRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *AddBarcodeRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type AddBarcodeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Barcode       *Barcode               `protobuf:"bytes,1,opt,name=barcode,proto3" json:"barcode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBarcodeReply) Reset() {
	*x = AddBarcodeReply{}
	mi := &file_api_products_v1_products_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBarcodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBarcodeReply) ProtoMessage() {}

func (x *AddBarcodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBarcodeReply.ProtoReflect.Descriptor instead.
func (*AddBarcodeReply) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{11}
}

func (x *AddBarcodeReply) GetBarcode() *Barcode {
	if x != nil {
		return x.Barcode
	}
	return nil
}

type RemoveBarcodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBarcodeRequest) Reset() {
	*x = RemoveBarcodeRequest{}
	mi := &file_api_products_v1_products_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBarcodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBarcodeRequest) ProtoMessage() {}

func (x *RemoveBarcodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBarcodeRequest.ProtoReflect.Descriptor instead.
func (*RemoveBarcodeRequest) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveBarcodeRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RemoveBarcodeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBarcodeReply) Reset() {
	*x = RemoveBarcodeReply{}
	mi := &file_api_products_v1_products_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBarcodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBarcodeReply) ProtoMessage() {}

func (x *RemoveBarcodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBarcodeReply.ProtoReflect.Descriptor instead.
func (*RemoveBarcodeReply) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{13}
}

type ListBarcodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBarcodesRequest) Reset() {
	*x = ListBarcodesRequest{}
	mi := &file_api_products_v1_products_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBarcodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBarcodesRequest) ProtoMessage() {}

func (x *ListBarcodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBarcodesRequest.ProtoReflect.Descriptor instead.
func (*ListBarcodesRequest) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{14}
}

func (x *ListBarcodesRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type ListBarcodesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Barcode             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBarcodesReply) Reset() {
	*x = ListBarcodesReply{}
	mi := &file_api_products_v1_products_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBarcodesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBarcodesReply) ProtoMessage() {}

func (x *ListBarcodesReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBarcodesReply.ProtoReflect.Descriptor instead.
func (*ListBarcodesReply) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{15}
}

func (x *ListBarcodesReply) GetItems() []*Barcode {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetProductByBarcodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Barcode       string                 `protobuf:"bytes,1,opt,name=barcode,proto3" json:"barcode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductByBarcodeRequest) Reset() {
	*x = GetProductByBarcodeRequest{}
	mi := &file_api_products_v1_products_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductByBarcodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductByBarcodeRequest) ProtoMessage() {}

func (x *GetProductByBarcodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductByBarcodeRequest.ProtoReflect.Descriptor instead.
func (*GetProductByBarcodeRequest) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{16}
}

func (x *GetProductByBarcodeRequest) GetBarcode() string {
	if x != nil {
		return x.Barcode
	}
	return ""
}

type GetProductByBarcodeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductByBarcodeReply) Reset() {
	*x = GetProductByBarcodeReply{}
	mi := &file_api_products_v1_products_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductByBarcodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductByBarcodeReply) ProtoMessage() {}

func (x *GetProductByBarcodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductByBarcodeReply.ProtoReflect.Descriptor instead.
func (*GetProductByBarcodeReply) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{17}
}

func (x *GetProductByBarcodeReply) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type SearchProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Paginate      *v1.PaginateRequest    `protobuf:"bytes,2,opt,name=paginate,proto3" json:"paginate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProductsRequest) Reset() {
	*x = SearchProductsRequest{}
	mi := &file_api_products_v1_products_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductsRequest) ProtoMessage() {}

func (x *SearchProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductsRequest.ProtoReflect.Descriptor instead.
func (*SearchProductsRequest) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{18}
}

func (x *SearchProductsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchProductsRequest) GetPaginate() *v1.PaginateRequest {
	if x != nil {
		return x.Paginate
	}
	return nil
}

type SearchProductsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Product             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Paginate      *v1.PaginateReply      `protobuf:"bytes,2,opt,name=paginate,proto3" json:"paginate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchProductsReply) Reset() {
	*x = SearchProductsReply{}
	mi := &file_api_products_v1_products_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchProductsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchProductsReply) ProtoMessage() {}

func (x *SearchProductsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchProductsReply.ProtoReflect.Descriptor instead.
func (*SearchProductsReply) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{19}
}

func (x *SearchProductsReply) GetItems() []*Product {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SearchProductsReply) GetPaginate() *v1.PaginateReply {
	if x != nil {
		return x.Paginate
	}
	return nil
}

type SetPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	PriceType     string                 `protobuf:"bytes,2,opt,name=price_type,json=priceType,proto3" json:"price_type,omitempty"`
	NewPrice      string                 `protobuf:"bytes,3,opt,name=new_price,json=newPrice,proto3" json:"new_price,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPriceRequest) Reset() {
	*x = SetPriceRequest{}
	mi := &file_api_products_v1_products_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPriceRequest) ProtoMessage() {}

func (x *SetPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPriceRequest.ProtoReflect.Descriptor instead.
func (*SetPriceRequest) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{20}
}

func (x *SetPriceRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *SetPriceRequest) GetPriceType() string {
	if x != nil {
		return x.PriceType
	}
	return ""
}

func (x *SetPriceRequest) GetNewPrice() string {
	if x != nil {
		return x.NewPrice
	}
	return ""
}

func (x *SetPriceRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SetPriceReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPriceReply) Reset() {
	*x = SetPriceReply{}
	mi := &file_api_products_v1_products_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPriceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPriceReply) ProtoMessage() {}

func (x *SetPriceReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPriceReply.ProtoReflect.Descriptor instead.
func (*SetPriceReply) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{21}
}

func (x *SetPriceReply) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type GetPriceHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int64                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	PriceType     string                 `protobuf:"bytes,2,opt,name=price_type,json=priceType,proto3" json:"price_type,omitempty"`
	Paginate      *v1.PaginateRequest    `protobuf:"bytes,3,opt,name=paginate,proto3" json:"paginate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceHistoryRequest) Reset() {
	*x = GetPriceHistoryRequest{}
	mi := &file_api_products_v1_products_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceHistoryRequest) ProtoMessage() {}

func (x *GetPriceHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetPriceHistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{22}
}

func (x *GetPriceHistoryRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *GetPriceHistoryRequest) GetPriceType() string {
	if x != nil {
		return x.PriceType
	}
	return ""
}

func (x *GetPriceHistoryRequest) GetPaginate() *v1.PaginateRequest {
	if x != nil {
		return x.Paginate
	}
	return nil
}

type GetPriceHistoryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*PriceHistory        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Paginate      *v1.PaginateReply      `protobuf:"bytes,2,opt,name=paginate,proto3" json:"paginate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPriceHistoryReply) Reset() {
	*x = GetPriceHistoryReply{}
	mi := &file_api_products_v1_products_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPriceHistoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceHistoryReply) ProtoMessage() {}

func (x *GetPriceHistoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceHistoryReply.ProtoReflect.Descriptor instead.
func (*GetPriceHistoryReply) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{23}
}

func (x *GetPriceHistoryReply) GetItems() []*PriceHistory {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetPriceHistoryReply) GetPaginate() *v1.PaginateReply {
	if x != nil {
		return x.Paginate
	}
	return nil
}

type CreateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ParentId      int64                  `protobuf:"varint,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryRequest) Reset() {
	*x = CreateCategoryRequest{}
	mi := &file_api_products_v1_products_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryRequest) ProtoMessage() {}

func (x *CreateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{24}
}

func (x *CreateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCategoryRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

type CreateCategoryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryReply) Reset() {
	*x = CreateCategoryReply{}
	mi := &file_api_products_v1_products_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryReply) ProtoMessage() {}

func (x *CreateCategoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryReply.ProtoReflect.Descriptor instead.
func (*CreateCategoryReply) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{25}
}

func (x *CreateCategoryReply) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type UpdateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentId      int64                  `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryRequest) Reset() {
	*x = UpdateCategoryRequest{}
	mi := &file_api_products_v1_products_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryRequest) ProtoMessage() {}

func (x *UpdateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateCategoryRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCategoryRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

type UpdateCategoryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryReply) Reset() {
	*x = UpdateCategoryReply{}
	mi := &file_api_products_v1_products_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryReply) ProtoMessage() {}

func (x *UpdateCategoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryReply.ProtoReflect.Descriptor instead.
func (*UpdateCategoryReply) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateCategoryReply) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type DeleteCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryRequest) Reset() {
	*x = DeleteCategoryRequest{}
	mi := &file_api_products_v1_products_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryRequest) ProtoMessage() {}

func (x *DeleteCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteCategoryRequest) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteCategoryRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteCategoryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryReply) Reset() {
	*x = DeleteCategoryReply{}
	mi := &file_api_products_v1_products_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryReply) ProtoMessage() {}

func (x *DeleteCategoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryReply.ProtoReflect.Descriptor instead.
func (*DeleteCategoryReply) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{29}
}

type GetCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	WithProducts  bool                   `protobuf:"varint,2,opt,name=with_products,json=withProducts,proto3" json:"with_products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryRequest) Reset() {
	*x = GetCategoryRequest{}
	mi := &file_api_products_v1_products_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryRequest) ProtoMessage() {}

func (x *GetCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryRequest.ProtoReflect.Descriptor instead.
func (*GetCategoryRequest) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{30}
}

func (x *GetCategoryRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetCategoryRequest) GetWithProducts() bool {
	if x != nil {
		return x.WithProducts
	}
	return false
}

type GetCategoryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Products      []*Product             `protobuf:"bytes,2,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryReply) Reset() {
	*x = GetCategoryReply{}
	mi := &file_api_products_v1_products_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryReply) ProtoMessage() {}

func (x *GetCategoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryReply.ProtoReflect.Descriptor instead.
func (*GetCategoryReply) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{31}
}

func (x *GetCategoryReply) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *GetCategoryReply) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type ListCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      int64                  `protobuf:"varint,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesRequest) Reset() {
	*x = ListCategoriesRequest{}
	mi := &file_api_products_v1_products_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesRequest) ProtoMessage() {}

func (x *ListCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{32}
}

func (x *ListCategoriesRequest) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

type ListCategoriesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Category            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesReply) Reset() {
	*x = ListCategoriesReply{}
	mi := &file_api_products_v1_products_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesReply) ProtoMessage() {}

func (x *ListCategoriesReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesReply.ProtoReflect.Descriptor instead.
func (*ListCategoriesReply) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{33}
}

func (x *ListCategoriesReply) GetItems() []*Category {
	if x != nil {
		return x.Items
	}
	return nil
}

type ColumnMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          int32                  `protobuf:"varint,1,opt,name=name,proto3" json:"name,omitempty"`
	Barcode       int32                  `protobuf:"varint,2,opt,name=barcode,proto3" json:"barcode,omitempty"`
	SellingPrice  int32                  `protobuf:"varint,3,opt,name=selling_price,json=sellingPrice,proto3" json:"selling_price,omitempty"`
	PurchasePrice int32                  `protobuf:"varint,4,opt,name=purchase_price,json=purchasePrice,proto3" json:"purchase_price,omitempty"`
	Category      int32                  `protobuf:"varint,5,opt,name=category,proto3" json:"category,omitempty"`
	Unit          int32                  `protobuf:"varint,6,opt,name=unit,proto3" json:"unit,omitempty"`
	Sku           int32                  `protobuf:"varint,7,opt,name=sku,proto3" json:"sku,omitempty"`
	Description   int32                  `protobuf:"varint,8,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColumnMapping) Reset() {
	*x = ColumnMapping{}
	mi := &file_api_products_v1_products_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColumnMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnMapping) ProtoMessage() {}

func (x *ColumnMapping) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnMapping.ProtoReflect.Descriptor instead.
func (*ColumnMapping) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{34}
}

func (x *ColumnMapping) GetName() int32 {
	if x != nil {
		return x.Name
	}
	return 0
}

func (x *ColumnMapping) GetBarcode() int32 {
	if x != nil {
		return x.Barcode
	}
	return 0
}

func (x *ColumnMapping) GetSellingPrice() int32 {
	if x != nil {
		return x.SellingPrice
	}
	return 0
}

func (x *ColumnMapping) GetPurchasePrice() int32 {
	if x != nil {
		return x.PurchasePrice
	}
	return 0
}

func (x *ColumnMapping) GetCategory() int32 {
	if x != nil {
		return x.Category
	}
	return 0
}

func (x *ColumnMapping) GetUnit() int32 {
	if x != nil {
		return x.Unit
	}
	return 0
}

func (x *ColumnMapping) GetSku() int32 {
	if x != nil {
		return x.Sku
	}
	return 0
}

func (x *ColumnMapping) GetDescription() int32 {
	if x != nil {
		return x.Description
	}
	return 0
}

type ImportRowError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           int32                  `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportRowError) Reset() {
	*x = ImportRowError{}
	mi := &file_api_products_v1_products_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportRowError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportRowError) ProtoMessage() {}

func (x *ImportRowError) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportRowError.ProtoReflect.Descriptor instead.
func (*ImportRowError) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{35}
}

func (x *ImportRowError) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *ImportRowError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ImportProductsRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	File                 []byte                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Format               ImportFormat           `protobuf:"varint,2,opt,name=format,proto3,enum=products.v1.ImportFormat" json:"format,omitempty"`
	Mapping              *ColumnMapping         `protobuf:"bytes,3,opt,name=mapping,proto3" json:"mapping,omitempty"`
	SkipHeader           bool                   `protobuf:"varint,4,opt,name=skip_header,json=skipHeader,proto3" json:"skip_header,omitempty"`
	AutoCreateCategories bool                   `protobuf:"varint,5,opt,name=auto_create_categories,json=autoCreateCategories,proto3" json:"auto_create_categories,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ImportProductsRequest) Reset() {
	*x = ImportProductsRequest{}
	mi := &file_api_products_v1_products_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportProductsRequest) ProtoMessage() {}

func (x *ImportProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportProductsRequest.ProtoReflect.Descriptor instead.
func (*ImportProductsRequest) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{36}
}

func (x *ImportProductsRequest) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *ImportProductsRequest) GetFormat() ImportFormat {
	if x != nil {
		return x.Format
	}
	return ImportFormat_CSV
}

func (x *ImportProductsRequest) GetMapping() *ColumnMapping {
	if x != nil {
		return x.Mapping
	}
	return nil
}

func (x *ImportProductsRequest) GetSkipHeader() bool {
	if x != nil {
		return x.SkipHeader
	}
	return false
}

func (x *ImportProductsRequest) GetAutoCreateCategories() bool {
	if x != nil {
		return x.AutoCreateCategories
	}
	return false
}

type ImportProductsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       int32                  `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Skipped       int32                  `protobuf:"varint,2,opt,name=skipped,proto3" json:"skipped,omitempty"`
	Errors        int32                  `protobuf:"varint,3,opt,name=errors,proto3" json:"errors,omitempty"`
	ErrorDetails  []*ImportRowError      `protobuf:"bytes,4,rep,name=error_details,json=errorDetails,proto3" json:"error_details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportProductsReply) Reset() {
	*x = ImportProductsReply{}
	mi := &file_api_products_v1_products_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportProductsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportProductsReply) ProtoMessage() {}

func (x *ImportProductsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportProductsReply.ProtoReflect.Descriptor instead.
func (*ImportProductsReply) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{37}
}

func (x *ImportProductsReply) GetCreated() int32 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ImportProductsReply) GetSkipped() int32 {
	if x != nil {
		return x.Skipped
	}
	return 0
}

func (x *ImportProductsReply) GetErrors() int32 {
	if x != nil {
		return x.Errors
	}
	return 0
}

func (x *ImportProductsReply) GetErrorDetails() []*ImportRowError {
	if x != nil {
		return x.ErrorDetails
	}
	return nil
}

type ImportFromUMAGRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          []byte                 `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportFromUMAGRequest) Reset() {
	*x = ImportFromUMAGRequest{}
	mi := &file_api_products_v1_products_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportFromUMAGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportFromUMAGRequest) ProtoMessage() {}

func (x *ImportFromUMAGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportFromUMAGRequest.ProtoReflect.Descriptor instead.
func (*ImportFromUMAGRequest) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{38}
}

func (x *ImportFromUMAGRequest) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

type ImportFromUMAGReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       int32                  `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Skipped       int32                  `protobuf:"varint,2,opt,name=skipped,proto3" json:"skipped,omitempty"`
	Errors        int32                  `protobuf:"varint,3,opt,name=errors,proto3" json:"errors,omitempty"`
	ErrorDetails  []*ImportRowError      `protobuf:"bytes,4,rep,name=error_details,json=errorDetails,proto3" json:"error_details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportFromUMAGReply) Reset() {
	*x = ImportFromUMAGReply{}
	mi := &file_api_products_v1_products_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportFromUMAGReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportFromUMAGReply) ProtoMessage() {}

func (x *ImportFromUMAGReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_products_v1_products_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportFromUMAGReply.ProtoReflect.Descriptor instead.
func (*ImportFromUMAGReply) Descriptor() ([]byte, []int) {
	return file_api_products_v1_products_proto_rawDescGZIP(), []int{39}
}

func (x *ImportFromUMAGReply) GetCreated() int32 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ImportFromUMAGReply) GetSkipped() int32 {
	if x != nil {
		return x.Skipped
	}
	return 0
}

func (x *ImportFromUMAGReply) GetErrors() int32 {
	if x != nil {
		return x.Errors
	}
	return 0
}

func (x *ImportFromUMAGReply) GetErrorDetails() []*ImportRowError {
	if x != nil {
		return x.ErrorDetails
	}
	return nil
}

var File_api_products_v1_products_proto protoreflect.FileDescriptor

const file_api_products_v1_products_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/products/v1/products.proto\x12\vproducts.v1\x1a\x1capi/products/v1/models.proto\x1a\x19api/utils/v1/models.proto\"\xf9\x01\n" +
	"\x14CreateProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\abarcode\x18\x02 \x01(\tR\abarcode\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04unit\x18\x04 \x01(\tR\x04unit\x12%\n" +
	"\x0epurchase_price\x18\x05 \x01(\tR\rpurchasePrice\x12#\n" +
	"\rselling_price\x18\x06 \x01(\tR\fsellingPrice\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12\x10\n" +
	"\x03sku\x18\b \x01(\tR\x03sku\"D\n" +
	"\x12CreateProductReply\x12.\n" +
	"\aproduct\x18\x01 \x01(\v2\x14.products.v1.ProductR\aproduct\"#\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"A\n" +
	"\x0fGetProductReply\x12.\n" +
	"\aproduct\x18\x01 \x01(\v2\x14.products.v1.ProductR\aproduct\"L\n" +
	"\x13ListProductsRequest\x125\n" +
	"\bpaginate\x18\x01 \x01(\v2\x19.utils.v1.PaginateRequestR\bpaginate\"t\n" +
	"\x11ListProductsReply\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.products.v1.ProductR\x05items\x123\n" +
	"\bpaginate\x18\x02 \x01(\v2\x17.utils.v1.PaginateReplyR\bpaginate\"\xa1\x02\n" +
	"\x14UpdateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\abarcode\x18\x03 \x01(\tR\abarcode\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04unit\x18\x05 \x01(\tR\x04unit\x12%\n" +
	"\x0epurchase_price\x18\x06 \x01(\tR\rpurchasePrice\x12#\n" +
	"\rselling_price\x18\a \x01(\tR\fsellingPrice\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x10\n" +
	"\x03sku\x18\t \x01(\tR\x03sku\x12\x16\n" +
	"\x06reason\x18\x0e \x01(\tR\x06reason\"D\n" +
	"\x12UpdateProductReply\x12.\n" +
	"\aproduct\x18\x01 \x01(\v2\x14.products.v1.ProductR\aproduct\"&\n" +
	"\x14DeleteProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x14\n" +
	"\x12DeleteProductReply\"\\\n" +
	"\x11AddBarcodeRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"A\n" +
	"\x0fAddBarcodeReply\x12.\n" +
	"\abarcode\x18\x01 \x01(\v2\x14.products.v1.BarcodeR\abarcode\"&\n" +
	"\x14RemoveBarcodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x14\n" +
	"\x12RemoveBarcodeReply\"4\n" +
	"\x13ListBarcodesRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\"?\n" +
	"\x11ListBarcodesReply\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.products.v1.BarcodeR\x05items\"6\n" +
	"\x1aGetProductByBarcodeRequest\x12\x18\n" +
	"\abarcode\x18\x01 \x01(\tR\abarcode\"J\n" +
	"\x18GetProductByBarcodeReply\x12.\n" +
	"\aproduct\x18\x01 \x01(\v2\x14.products.v1.ProductR\aproduct\"d\n" +
	"\x15SearchProductsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x125\n" +
	"\bpaginate\x18\x02 \x01(\v2\x19.utils.v1.PaginateRequestR\bpaginate\"v\n" +
	"\x13SearchProductsReply\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.products.v1.ProductR\x05items\x123\n" +
	"\bpaginate\x18\x02 \x01(\v2\x17.utils.v1.PaginateReplyR\bpaginate\"\x84\x01\n" +
	"\x0fSetPriceRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x1d\n" +
	"\n" +
	"price_type\x18\x02 \x01(\tR\tpriceType\x12\x1b\n" +
	"\tnew_price\x18\x03 \x01(\tR\bnewPrice\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"?\n" +
	"\rSetPriceReply\x12.\n" +
	"\aproduct\x18\x01 \x01(\v2\x14.products.v1.ProductR\aproduct\"\x8d\x01\n" +
	"\x16GetPriceHistoryRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x1d\n" +
	"\n" +
	"price_type\x18\x02 \x01(\tR\tpriceType\x125\n" +
	"\bpaginate\x18\x03 \x01(\v2\x19.utils.v1.PaginateRequestR\bpaginate\"|\n" +
	"\x14GetPriceHistoryReply\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.products.v1.PriceHistoryR\x05items\x123\n" +
	"\bpaginate\x18\x02 \x01(\v2\x17.utils.v1.PaginateReplyR\bpaginate\"H\n" +
	"\x15CreateCategoryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\x03R\bparentId\"H\n" +
	"\x13CreateCategoryReply\x121\n" +
	"\bcategory\x18\x01 \x01(\v2\x15.products.v1.CategoryR\bcategory\"X\n" +
	"\x15UpdateCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\x03R\bparentId\"H\n" +
	"\x13UpdateCategoryReply\x121\n" +
	"\bcategory\x18\x01 \x01(\v2\x15.products.v1.CategoryR\bcategory\"'\n" +
	"\x15DeleteCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x15\n" +
	"\x13DeleteCategoryReply\"I\n" +
	"\x12GetCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12#\n" +
	"\rwith_products\x18\x02 \x01(\bR\fwithProducts\"w\n" +
	"\x10GetCategoryReply\x121\n" +
	"\bcategory\x18\x01 \x01(\v2\x15.products.v1.CategoryR\bcategory\x120\n" +
	"\bproducts\x18\x02 \x03(\v2\x14.products.v1.ProductR\bproducts\"4\n" +
	"\x15ListCategoriesRequest\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\x03R\bparentId\"B\n" +
	"\x13ListCategoriesReply\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.products.v1.CategoryR\x05items\"\xed\x01\n" +
	"\rColumnMapping\x12\x12\n" +
	"\x04name\x18\x01 \x01(\x05R\x04name\x12\x18\n" +
	"\abarcode\x18\x02 \x01(\x05R\abarcode\x12#\n" +
	"\rselling_price\x18\x03 \x01(\x05R\fsellingPrice\x12%\n" +
	"\x0epurchase_price\x18\x04 \x01(\x05R\rpurchasePrice\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\x05R\bcategory\x12\x12\n" +
	"\x04unit\x18\x06 \x01(\x05R\x04unit\x12\x10\n" +
	"\x03sku\x18\a \x01(\x05R\x03sku\x12 \n" +
	"\vdescription\x18\b \x01(\x05R\vdescription\"<\n" +
	"\x0eImportRowError\x12\x10\n" +
	"\x03row\x18\x01 \x01(\x05R\x03row\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xeb\x01\n" +
	"\x15ImportProductsRequest\x12\x12\n" +
	"\x04file\x18\x01 \x01(\fR\x04file\x121\n" +
	"\x06format\x18\x02 \x01(\x0e2\x19.products.v1.ImportFormatR\x06format\x124\n" +
	"\amapping\x18\x03 \x01(\v2\x1a.products.v1.ColumnMappingR\amapping\x12\x1f\n" +
	"\vskip_header\x18\x04 \x01(\bR\n" +
	"skipHeader\x124\n" +
	"\x16auto_create_categories\x18\x05 \x01(\bR\x14autoCreateCategories\"\xa3\x01\n" +
	"\x13ImportProductsReply\x12\x18\n" +
	"\acreated\x18\x01 \x01(\x05R\acreated\x12\x18\n" +
	"\askipped\x18\x02 \x01(\x05R\askipped\x12\x16\n" +
	"\x06errors\x18\x03 \x01(\x05R\x06errors\x12@\n" +
	"\rerror_details\x18\x04 \x03(\v2\x1b.products.v1.ImportRowErrorR\ferrorDetails\"+\n" +
	"\x15ImportFromUMAGRequest\x12\x12\n" +
	"\x04file\x18\x01 \x01(\fR\x04file\"\xa3\x01\n" +
	"\x13ImportFromUMAGReply\x12\x18\n" +
	"\acreated\x18\x01 \x01(\x05R\acreated\x12\x18\n" +
	"\askipped\x18\x02 \x01(\x05R\askipped\x12\x16\n" +
	"\x06errors\x18\x03 \x01(\x05R\x06errors\x12@\n" +
	"\rerror_details\x18\x04 \x03(\v2\x1b.products.v1.ImportRowErrorR\ferrorDetails*!\n" +
	"\fImportFormat\x12\a\n" +
	"\x03CSV\x10\x00\x12\b\n" +
	"\x04XLSX\x10\x012\xe0\f\n" +
	"\x0fProductsService\x12S\n" +
	"\rCreateProduct\x12!.products.v1.CreateProductRequest\x1a\x1f.products.v1.CreateProductReply\x12J\n" +
	"\n" +
	"GetProduct\x12\x1e.products.v1.GetProductRequest\x1a\x1c.products.v1.GetProductReply\x12P\n" +
	"\fListProducts\x12 .products.v1.ListProductsRequest\x1a\x1e.products.v1.ListProductsReply\x12S\n" +
	"\rUpdateProduct\x12!.products.v1.UpdateProductRequest\x1a\x1f.products.v1.UpdateProductReply\x12S\n" +
	"\rDeleteProduct\x12!.products.v1.DeleteProductRequest\x1a\x1f.products.v1.DeleteProductReply\x12J\n" +
	"\n" +
	"AddBarcode\x12\x1e.products.v1.AddBarcodeRequest\x1a\x1c.products.v1.AddBarcodeReply\x12S\n" +
	"\rRemoveBarcode\x12!.products.v1.RemoveBarcodeRequest\x1a\x1f.products.v1.RemoveBarcodeReply\x12P\n" +
	"\fListBarcodes\x12 .products.v1.ListBarcodesRequest\x1a\x1e.products.v1.ListBarcodesReply\x12e\n" +
	"\x13GetProductByBarcode\x12'.products.v1.GetProductByBarcodeRequest\x1a%.products.v1.GetProductByBarcodeReply\x12V\n" +
	"\x0eSearchProducts\x12\".products.v1.SearchProductsRequest\x1a .products.v1.SearchProductsReply\x12D\n" +
	"\bSetPrice\x12\x1c.products.v1.SetPriceRequest\x1a\x1a.products.v1.SetPriceReply\x12Y\n" +
	"\x0fGetPriceHistory\x12#.products.v1.GetPriceHistoryRequest\x1a!.products.v1.GetPriceHistoryReply\x12V\n" +
	"\x0eCreateCategory\x12\".products.v1.CreateCategoryRequest\x1a .products.v1.CreateCategoryReply\x12V\n" +
	"\x0eUpdateCategory\x12\".products.v1.UpdateCategoryRequest\x1a .products.v1.UpdateCategoryReply\x12V\n" +
	"\x0eDeleteCategory\x12\".products.v1.DeleteCategoryRequest\x1a .products.v1.DeleteCategoryReply\x12M\n" +
	"\vGetCategory\x12\x1f.products.v1.GetCategoryRequest\x1a\x1d.products.v1.GetCategoryReply\x12V\n" +
	"\x0eListCategories\x12\".products.v1.ListCategoriesRequest\x1a .products.v1.ListCategoriesReply\x12V\n" +
	"\x0eImportProducts\x12\".products.v1.ImportProductsRequest\x1a .products.v1.ImportProductsReply\x12V\n" +
	"\x0eImportFromUMAG\x12\".products.v1.ImportFromUMAGRequest\x1a .products.v1.ImportFromUMAGReplyBFZDgithub.com/makesalekz/products/api/products/v1;products_v1b\x06proto3"

var (
	file_api_products_v1_products_proto_rawDescOnce sync.Once
	file_api_products_v1_products_proto_rawDescData []byte
)

func file_api_products_v1_products_proto_rawDescGZIP() []byte {
	file_api_products_v1_products_proto_rawDescOnce.Do(func() {
		file_api_products_v1_products_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_products_v1_products_proto_rawDesc), len(file_api_products_v1_products_proto_rawDesc)))
	})
	return file_api_products_v1_products_proto_rawDescData
}

var file_api_products_v1_products_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_products_v1_products_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_api_products_v1_products_proto_goTypes = []any{
	(ImportFormat)(0),                  // 0: products.v1.ImportFormat
	(*CreateProductRequest)(nil),       // 1: products.v1.CreateProductRequest
	(*CreateProductReply)(nil),         // 2: products.v1.CreateProductReply
	(*GetProductRequest)(nil),          // 3: products.v1.GetProductRequest
	(*GetProductReply)(nil),            // 4: products.v1.GetProductReply
	(*ListProductsRequest)(nil),        // 5: products.v1.ListProductsRequest
	(*ListProductsReply)(nil),          // 6: products.v1.ListProductsReply
	(*UpdateProductRequest)(nil),       // 7: products.v1.UpdateProductRequest
	(*UpdateProductReply)(nil),         // 8: products.v1.UpdateProductReply
	(*DeleteProductRequest)(nil),       // 9: products.v1.DeleteProductRequest
	(*DeleteProductReply)(nil),         // 10: products.v1.DeleteProductReply
	(*AddBarcodeRequest)(nil),          // 11: products.v1.AddBarcodeRequest
	(*AddBarcodeReply)(nil),            // 12: products.v1.AddBarcodeReply
	(*RemoveBarcodeRequest)(nil),       // 13: products.v1.RemoveBarcodeRequest
	(*RemoveBarcodeReply)(nil),         // 14: products.v1.RemoveBarcodeReply
	(*ListBarcodesRequest)(nil),        // 15: products.v1.ListBarcodesRequest
	(*ListBarcodesReply)(nil),          // 16: products.v1.ListBarcodesReply
	(*GetProductByBarcodeRequest)(nil), // 17: products.v1.GetProductByBarcodeRequest
	(*GetProductByBarcodeReply)(nil),   // 18: products.v1.GetProductByBarcodeReply
	(*SearchProductsRequest)(nil),      // 19: products.v1.SearchProductsRequest
	(*SearchProductsReply)(nil),        // 20: products.v1.SearchProductsReply
	(*SetPriceRequest)(nil),            // 21: products.v1.SetPriceRequest
	(*SetPriceReply)(nil),              // 22: products.v1.SetPriceReply
	(*GetPriceHistoryRequest)(nil),     // 23: products.v1.GetPriceHistoryRequest
	(*GetPriceHistoryReply)(nil),       // 24: products.v1.GetPriceHistoryReply
	(*CreateCategoryRequest)(nil),      // 25: products.v1.CreateCategoryRequest
	(*CreateCategoryReply)(nil),        // 26: products.v1.CreateCategoryReply
	(*UpdateCategoryRequest)(nil),      // 27: products.v1.UpdateCategoryRequest
	(*UpdateCategoryReply)(nil),        // 28: products.v1.UpdateCategoryReply
	(*DeleteCategoryRequest)(nil),      // 29: products.v1.DeleteCategoryRequest
	(*DeleteCategoryReply)(nil),        // 30: products.v1.DeleteCategoryReply
	(*GetCategoryRequest)(nil),         // 31: products.v1.GetCategoryRequest
	(*GetCategoryReply)(nil),           // 32: products.v1.GetCategoryReply
	(*ListCategoriesRequest)(nil),      // 33: products.v1.ListCategoriesRequest
	(*ListCategoriesReply)(nil),        // 34: products.v1.ListCategoriesReply
	(*ColumnMapping)(nil),              // 35: products.v1.ColumnMapping
	(*ImportRowError)(nil),             // 36: products.v1.ImportRowError
	(*ImportProductsRequest)(nil),      // 37: products.v1.ImportProductsRequest
	(*ImportProductsReply)(nil),        // 38: products.v1.ImportProductsReply
	(*ImportFromUMAGRequest)(nil),      // 39: products.v1.ImportFromUMAGRequest
	(*ImportFromUMAGReply)(nil),        // 40: products.v1.ImportFromUMAGReply
	(*Product)(nil),                    // 41: products.v1.Product
	(*v1.PaginateRequest)(nil),         // 42: utils.v1.PaginateRequest
	(*v1.PaginateReply)(nil),           // 43: utils.v1.PaginateReply
	(*Barcode)(nil),                    // 44: products.v1.Barcode
	(*PriceHistory)(nil),               // 45: products.v1.PriceHistory
	(*Category)(nil),                   // 46: products.v1.Category
}
var file_api_products_v1_products_proto_depIdxs = []int32{
	41, // 0: products.v1.CreateProductReply.product:type_name -> products.v1.Product
	41, // 1: products.v1.GetProductReply.product:type_name -> products.v1.Product
	42, // 2: products.v1.ListProductsRequest.paginate:type_name -> utils.v1.PaginateRequest
	41, // 3: products.v1.ListProductsReply.items:type_name -> products.v1.Product
	43, // 4: products.v1.ListProductsReply.paginate:type_name -> utils.v1.PaginateReply
	41, // 5: products.v1.UpdateProductReply.product:type_name -> products.v1.Product
	44, // 6: products.v1.AddBarcodeReply.barcode:type_name -> products.v1.Barcode
	44, // 7: products.v1.ListBarcodesReply.items:type_name -> products.v1.Barcode
	41, // 8: products.v1.GetProductByBarcodeReply.product:type_name -> products.v1.Product
	42, // 9: products.v1.SearchProductsRequest.paginate:type_name -> utils.v1.PaginateRequest
	41, // 10: products.v1.SearchProductsReply.items:type_name -> products.v1.Product
	43, // 11: products.v1.SearchProductsReply.paginate:type_name -> utils.v1.PaginateReply
	41, // 12: products.v1.SetPriceReply.product:type_name -> products.v1.Product
	42, // 13: products.v1.GetPriceHistoryRequest.paginate:type_name -> utils.v1.PaginateRequest
	45, // 14: products.v1.GetPriceHistoryReply.items:type_name -> products.v1.PriceHistory
	43, // 15: products.v1.GetPriceHistoryReply.paginate:type_name -> utils.v1.PaginateReply
	46, // 16: products.v1.CreateCategoryReply.category:type_name -> products.v1.Category
	46, // 17: products.v1.UpdateCategoryReply.category:type_name -> products.v1.Category
	46, // 18: products.v1.GetCategoryReply.category:type_name -> products.v1.Category
	41, // 19: products.v1.GetCategoryReply.products:type_name -> products.v1.Product
	46, // 20: products.v1.ListCategoriesReply.items:type_name -> products.v1.Category
	0,  // 21: products.v1.ImportProductsRequest.format:type_name -> products.v1.ImportFormat
	35, // 22: products.v1.ImportProductsRequest.mapping:type_name -> products.v1.ColumnMapping
	36, // 23: products.v1.ImportProductsReply.error_details:type_name -> products.v1.ImportRowError
	36, // 24: products.v1.ImportFromUMAGReply.error_details:type_name -> products.v1.ImportRowError
	1,  // 25: products.v1.ProductsService.CreateProduct:input_type -> products.v1.CreateProductRequest
	3,  // 26: products.v1.ProductsService.GetProduct:input_type -> products.v1.GetProductRequest
	5,  // 27: products.v1.ProductsService.ListProducts:input_type -> products.v1.ListProductsRequest
	7,  // 28: products.v1.ProductsService.UpdateProduct:input_type -> products.v1.UpdateProductRequest
	9,  // 29: products.v1.ProductsService.DeleteProduct:input_type -> products.v1.DeleteProductRequest
	11, // 30: products.v1.ProductsService.AddBarcode:input_type -> products.v1.AddBarcodeRequest
	13, // 31: products.v1.ProductsService.RemoveBarcode:input_type -> products.v1.RemoveBarcodeRequest
	15, // 32: products.v1.ProductsService.ListBarcodes:input_type -> products.v1.ListBarcodesRequest
	17, // 33: products.v1.ProductsService.GetProductByBarcode:input_type -> products.v1.GetProductByBarcodeRequest
	19, // 34: products.v1.ProductsService.SearchProducts:input_type -> products.v1.SearchProductsRequest
	21, // 35: products.v1.ProductsService.SetPrice:input_type -> products.v1.SetPriceRequest
	23, // 36: products.v1.ProductsService.GetPriceHistory:input_type -> products.v1.GetPriceHistoryRequest
	25, // 37: products.v1.ProductsService.CreateCategory:input_type -> products.v1.CreateCategoryRequest
	27, // 38: products.v1.ProductsService.UpdateCategory:input_type -> products.v1.UpdateCategoryRequest
	29, // 39: products.v1.ProductsService.DeleteCategory:input_type -> products.v1.DeleteCategoryRequest
	31, // 40: products.v1.ProductsService.GetCategory:input_type -> products.v1.GetCategoryRequest
	33, // 41: products.v1.ProductsService.ListCategories:input_type -> products.v1.ListCategoriesRequest
	37, // 42: products.v1.ProductsService.ImportProducts:input_type -> products.v1.ImportProductsRequest
	39, // 43: products.v1.ProductsService.ImportFromUMAG:input_type -> products.v1.ImportFromUMAGRequest
	2,  // 44: products.v1.ProductsService.CreateProduct:output_type -> products.v1.CreateProductReply
	4,  // 45: products.v1.ProductsService.GetProduct:output_type -> products.v1.GetProductReply
	6,  // 46: products.v1.ProductsService.ListProducts:output_type -> products.v1.ListProductsReply
	8,  // 47: products.v1.ProductsService.UpdateProduct:output_type -> products.v1.UpdateProductReply
	10, // 48: products.v1.ProductsService.DeleteProduct:output_type -> products.v1.DeleteProductReply
	12, // 49: products.v1.ProductsService.AddBarcode:output_type -> products.v1.AddBarcodeReply
	14, // 50: products.v1.ProductsService.RemoveBarcode:output_type -> products.v1.RemoveBarcodeReply
	16, // 51: products.v1.ProductsService.ListBarcodes:output_type -> products.v1.ListBarcodesReply
	18, // 52: products.v1.ProductsService.GetProductByBarcode:output_type -> products.v1.GetProductByBarcodeReply
	20, // 53: products.v1.ProductsService.SearchProducts:output_type -> products.v1.SearchProductsReply
	22, // 54: products.v1.ProductsService.SetPrice:output_type -> products.v1.SetPriceReply
	24, // 55: products.v1.ProductsService.GetPriceHistory:output_type -> products.v1.GetPriceHistoryReply
	26, // 56: products.v1.ProductsService.CreateCategory:output_type -> products.v1.CreateCategoryReply
	28, // 57: products.v1.ProductsService.UpdateCategory:output_type -> products.v1.UpdateCategoryReply
	30, // 58: products.v1.ProductsService.DeleteCategory:output_type -> products.v1.DeleteCategoryReply
	32, // 59: products.v1.ProductsService.GetCategory:output_type -> products.v1.GetCategoryReply
	34, // 60: products.v1.ProductsService.ListCategories:output_type -> products.v1.ListCategoriesReply
	38, // 61: products.v1.ProductsService.ImportProducts:output_type -> products.v1.ImportProductsReply
	40, // 62: products.v1.ProductsService.ImportFromUMAG:output_type -> products.v1.ImportFromUMAGReply
	44, // [44:63] is the sub-list for method output_type
	25, // [25:44] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_api_products_v1_products_proto_init() }
func file_api_products_v1_products_proto_init() {
	if File_api_products_v1_products_proto != nil {
		return
	}
	file_api_products_v1_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_products_v1_products_proto_rawDesc), len(file_api_products_v1_products_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_products_v1_products_proto_goTypes,
		DependencyIndexes: file_api_products_v1_products_proto_depIdxs,
		EnumInfos:         file_api_products_v1_products_proto_enumTypes,
		MessageInfos:      file_api_products_v1_products_proto_msgTypes,
	}.Build()
	File_api_products_v1_products_proto = out.File
	file_api_products_v1_products_proto_goTypes = nil
	file_api_products_v1_products_proto_depIdxs = nil
}
