// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"gitlab.calendaria.team/services/products/internal/biz"
	"gitlab.calendaria.team/services/products/internal/conf"
	"gitlab.calendaria.team/services/products/internal/data"
	"gitlab.calendaria.team/services/products/internal/server"
	"gitlab.calendaria.team/services/products/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(bootstrap, logger)
	if err != nil {
		return nil, nil, err
	}
	productsRepo := data.NewProductsRepo(dataData)
	barcodesRepo := data.NewBarcodesRepo(dataData)
	priceHistoriesRepo := data.NewPriceHistoriesRepo(dataData)
	categoriesRepo := data.NewCategoriesRepo(dataData)
	productsUsecase := biz.NewProductsUsecase(logger, productsRepo, barcodesRepo, priceHistoriesRepo, categoriesRepo)
	productsService := service.NewProductsService(productsUsecase)
	grpcServer := server.NewGRPCServer(bootstrap, productsService)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
