// Code generated by ent, DO NOT EDIT.

package product

import (
	"fmt"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/makesalekz/products/ent/enum"
)

const (
	// Label holds the string label denoting the product type in the database.
	Label = "product"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldBarcode holds the string denoting the barcode field in the database.
	FieldBarcode = "barcode"
	// FieldCategoryID holds the string denoting the category_id field in the database.
	FieldCategoryID = "category_id"
	// FieldUnit holds the string denoting the unit field in the database.
	FieldUnit = "unit"
	// FieldPurchasePrice holds the string denoting the purchase_price field in the database.
	FieldPurchasePrice = "purchase_price"
	// FieldSellingPrice holds the string denoting the selling_price field in the database.
	FieldSellingPrice = "selling_price"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldSku holds the string denoting the sku field in the database.
	FieldSku = "sku"
	// EdgeBarcodes holds the string denoting the barcodes edge name in mutations.
	EdgeBarcodes = "barcodes"
	// EdgePriceHistories holds the string denoting the price_histories edge name in mutations.
	EdgePriceHistories = "price_histories"
	// Table holds the table name of the product in the database.
	Table = "products"
	// BarcodesTable is the table that holds the barcodes relation/edge.
	BarcodesTable = "barcodes"
	// BarcodesInverseTable is the table name for the Barcode entity.
	// It exists in this package in order to avoid circular dependency with the "barcode" package.
	BarcodesInverseTable = "barcodes"
	// BarcodesColumn is the table column denoting the barcodes relation/edge.
	BarcodesColumn = "product_id"
	// PriceHistoriesTable is the table that holds the price_histories relation/edge.
	PriceHistoriesTable = "price_histories"
	// PriceHistoriesInverseTable is the table name for the PriceHistory entity.
	// It exists in this package in order to avoid circular dependency with the "pricehistory" package.
	PriceHistoriesInverseTable = "price_histories"
	// PriceHistoriesColumn is the table column denoting the price_histories relation/edge.
	PriceHistoriesColumn = "product_id"
)

// Columns holds all SQL columns for product fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldTenantID,
	FieldName,
	FieldBarcode,
	FieldCategoryID,
	FieldUnit,
	FieldPurchasePrice,
	FieldSellingPrice,
	FieldDescription,
	FieldSku,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/makesalekz/products/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultBarcode holds the default value on creation for the "barcode" field.
	DefaultBarcode string
	// DefaultCategoryID holds the default value on creation for the "category_id" field.
	DefaultCategoryID int64
	// DefaultDescription holds the default value on creation for the "description" field.
	DefaultDescription string
	// DefaultSku holds the default value on creation for the "sku" field.
	DefaultSku string
)

const DefaultUnit enum.UnitType = "PIECE"

// UnitValidator is a validator for the "unit" field enum values. It is called by the builders before save.
func UnitValidator(u enum.UnitType) error {
	switch u {
	case "PIECE", "KG", "LITER", "PACK", "BLOCK":
		return nil
	default:
		return fmt.Errorf("product: invalid enum value for unit field: %q", u)
	}
}

// OrderOption defines the ordering options for the Product queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByBarcode orders the results by the barcode field.
func ByBarcode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBarcode, opts...).ToFunc()
}

// ByCategoryID orders the results by the category_id field.
func ByCategoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCategoryID, opts...).ToFunc()
}

// ByUnit orders the results by the unit field.
func ByUnit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUnit, opts...).ToFunc()
}

// ByPurchasePrice orders the results by the purchase_price field.
func ByPurchasePrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPurchasePrice, opts...).ToFunc()
}

// BySellingPrice orders the results by the selling_price field.
func BySellingPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSellingPrice, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// BySku orders the results by the sku field.
func BySku(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSku, opts...).ToFunc()
}

// ByBarcodesCount orders the results by barcodes count.
func ByBarcodesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBarcodesStep(), opts...)
	}
}

// ByBarcodes orders the results by barcodes terms.
func ByBarcodes(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBarcodesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPriceHistoriesCount orders the results by price_histories count.
func ByPriceHistoriesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPriceHistoriesStep(), opts...)
	}
}

// ByPriceHistories orders the results by price_histories terms.
func ByPriceHistories(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPriceHistoriesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newBarcodesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BarcodesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BarcodesTable, BarcodesColumn),
	)
}
func newPriceHistoriesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PriceHistoriesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PriceHistoriesTable, PriceHistoriesColumn),
	)
}
