// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BarcodesColumns holds the columns for the "barcodes" table.
	BarcodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "tenant_id", Type: field.TypeInt64},
		{Name: "value", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"EAN13", "EAN8", "INTERNAL"}, Default: "EAN13"},
		{Name: "product_id", Type: field.TypeInt64},
	}
	// BarcodesTable holds the schema information for the "barcodes" table.
	BarcodesTable = &schema.Table{
		Name:       "barcodes",
		Columns:    BarcodesColumns,
		PrimaryKey: []*schema.Column{BarcodesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "barcodes_products_barcodes",
				Columns:    []*schema.Column{BarcodesColumns[6]},
				RefColumns: []*schema.Column{ProductsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "barcode_tenant_id_value",
				Unique:  true,
				Columns: []*schema.Column{BarcodesColumns[3], BarcodesColumns[4]},
			},
		},
	}
	// CategoriesColumns holds the columns for the "categories" table.
	CategoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64},
		{Name: "name", Type: field.TypeString},
		{Name: "parent_id", Type: field.TypeInt64, Nullable: true},
	}
	// CategoriesTable holds the schema information for the "categories" table.
	CategoriesTable = &schema.Table{
		Name:       "categories",
		Columns:    CategoriesColumns,
		PrimaryKey: []*schema.Column{CategoriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "categories_categories_children",
				Columns:    []*schema.Column{CategoriesColumns[6]},
				RefColumns: []*schema.Column{CategoriesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "category_tenant_id_parent_id_name",
				Unique:  true,
				Columns: []*schema.Column{CategoriesColumns[4], CategoriesColumns[6], CategoriesColumns[5]},
			},
		},
	}
	// PriceHistoriesColumns holds the columns for the "price_histories" table.
	PriceHistoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "tenant_id", Type: field.TypeInt64},
		{Name: "price_type", Type: field.TypeEnum, Enums: []string{"SELLING", "PURCHASE"}},
		{Name: "old_price", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "numeric"}},
		{Name: "new_price", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "numeric"}},
		{Name: "changed_by", Type: field.TypeInt64},
		{Name: "reason", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "changed_at", Type: field.TypeTime},
		{Name: "product_id", Type: field.TypeInt64},
	}
	// PriceHistoriesTable holds the schema information for the "price_histories" table.
	PriceHistoriesTable = &schema.Table{
		Name:       "price_histories",
		Columns:    PriceHistoriesColumns,
		PrimaryKey: []*schema.Column{PriceHistoriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "price_histories_products_price_histories",
				Columns:    []*schema.Column{PriceHistoriesColumns[10]},
				RefColumns: []*schema.Column{ProductsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "pricehistory_tenant_id_product_id_price_type",
				Unique:  false,
				Columns: []*schema.Column{PriceHistoriesColumns[3], PriceHistoriesColumns[10], PriceHistoriesColumns[4]},
			},
		},
	}
	// ProductsColumns holds the columns for the "products" table.
	ProductsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt64},
		{Name: "name", Type: field.TypeString},
		{Name: "barcode", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "category_id", Type: field.TypeInt64, Nullable: true, Default: 0},
		{Name: "unit", Type: field.TypeEnum, Enums: []string{"PIECE", "KG", "LITER", "PACK", "BLOCK"}, Default: "PIECE"},
		{Name: "purchase_price", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "numeric"}},
		{Name: "selling_price", Type: field.TypeFloat64, Nullable: true, SchemaType: map[string]string{"postgres": "numeric"}},
		{Name: "description", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "sku", Type: field.TypeString, Nullable: true, Default: ""},
	}
	// ProductsTable holds the schema information for the "products" table.
	ProductsTable = &schema.Table{
		Name:       "products",
		Columns:    ProductsColumns,
		PrimaryKey: []*schema.Column{ProductsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "product_tenant_id_barcode",
				Unique:  true,
				Columns: []*schema.Column{ProductsColumns[4], ProductsColumns[6]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BarcodesTable,
		CategoriesTable,
		PriceHistoriesTable,
		ProductsTable,
	}
)

func init() {
	BarcodesTable.ForeignKeys[0].RefTable = ProductsTable
	CategoriesTable.ForeignKeys[0].RefTable = CategoriesTable
	PriceHistoriesTable.ForeignKeys[0].RefTable = ProductsTable
}
