// Code generated by ent, DO NOT EDIT.

package pricehistory

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/makesalekz/products/ent/enum"
)

const (
	// Label holds the string label denoting the pricehistory type in the database.
	Label = "price_history"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldProductID holds the string denoting the product_id field in the database.
	FieldProductID = "product_id"
	// FieldPriceType holds the string denoting the price_type field in the database.
	FieldPriceType = "price_type"
	// FieldOldPrice holds the string denoting the old_price field in the database.
	FieldOldPrice = "old_price"
	// FieldNewPrice holds the string denoting the new_price field in the database.
	FieldNewPrice = "new_price"
	// FieldChangedBy holds the string denoting the changed_by field in the database.
	FieldChangedBy = "changed_by"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldChangedAt holds the string denoting the changed_at field in the database.
	FieldChangedAt = "changed_at"
	// EdgeProduct holds the string denoting the product edge name in mutations.
	EdgeProduct = "product"
	// Table holds the table name of the pricehistory in the database.
	Table = "price_histories"
	// ProductTable is the table that holds the product relation/edge.
	ProductTable = "price_histories"
	// ProductInverseTable is the table name for the Product entity.
	// It exists in this package in order to avoid circular dependency with the "product" package.
	ProductInverseTable = "products"
	// ProductColumn is the table column denoting the product relation/edge.
	ProductColumn = "product_id"
)

// Columns holds all SQL columns for pricehistory fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldTenantID,
	FieldProductID,
	FieldPriceType,
	FieldOldPrice,
	FieldNewPrice,
	FieldChangedBy,
	FieldReason,
	FieldChangedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultReason holds the default value on creation for the "reason" field.
	DefaultReason string
	// DefaultChangedAt holds the default value on creation for the "changed_at" field.
	DefaultChangedAt func() time.Time
)

// PriceTypeValidator is a validator for the "price_type" field enum values. It is called by the builders before save.
func PriceTypeValidator(pt enum.PriceType) error {
	switch pt {
	case "SELLING", "PURCHASE":
		return nil
	default:
		return fmt.Errorf("pricehistory: invalid enum value for price_type field: %q", pt)
	}
}

// OrderOption defines the ordering options for the PriceHistory queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByProductID orders the results by the product_id field.
func ByProductID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductID, opts...).ToFunc()
}

// ByPriceType orders the results by the price_type field.
func ByPriceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriceType, opts...).ToFunc()
}

// ByOldPrice orders the results by the old_price field.
func ByOldPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOldPrice, opts...).ToFunc()
}

// ByNewPrice orders the results by the new_price field.
func ByNewPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNewPrice, opts...).ToFunc()
}

// ByChangedBy orders the results by the changed_by field.
func ByChangedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChangedBy, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByChangedAt orders the results by the changed_at field.
func ByChangedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChangedAt, opts...).ToFunc()
}

// ByProductField orders the results by product field.
func ByProductField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProductStep(), sql.OrderByField(field, opts...))
	}
}
func newProductStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProductInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ProductTable, ProductColumn),
	)
}
