// Code generated by ent, DO NOT EDIT.

package pricehistory

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/shopspring/decimal"
	"github.com/makesalekz/products/ent/enum"
	"github.com/makesalekz/products/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldEQ(FieldTenantID, v))
}

// ProductID applies equality check predicate on the "product_id" field. It's identical to ProductIDEQ.
func ProductID(v int64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldEQ(FieldProductID, v))
}

// OldPrice applies equality check predicate on the "old_price" field. It's identical to OldPriceEQ.
func OldPrice(v decimal.Decimal) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldEQ(FieldOldPrice, v))
}

// NewPrice applies equality check predicate on the "new_price" field. It's identical to NewPriceEQ.
func NewPrice(v decimal.Decimal) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldEQ(FieldNewPrice, v))
}

// ChangedBy applies equality check predicate on the "changed_by" field. It's identical to ChangedByEQ.
func ChangedBy(v int64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldEQ(FieldChangedBy, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldEQ(FieldReason, v))
}

// ChangedAt applies equality check predicate on the "changed_at" field. It's identical to ChangedAtEQ.
func ChangedAt(v time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldEQ(FieldChangedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldLTE(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v int64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v int64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v int64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v int64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldLTE(FieldTenantID, v))
}

// ProductIDEQ applies the EQ predicate on the "product_id" field.
func ProductIDEQ(v int64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldEQ(FieldProductID, v))
}

// ProductIDNEQ applies the NEQ predicate on the "product_id" field.
func ProductIDNEQ(v int64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldNEQ(FieldProductID, v))
}

// ProductIDIn applies the In predicate on the "product_id" field.
func ProductIDIn(vs ...int64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldIn(FieldProductID, vs...))
}

// ProductIDNotIn applies the NotIn predicate on the "product_id" field.
func ProductIDNotIn(vs ...int64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldNotIn(FieldProductID, vs...))
}

// PriceTypeEQ applies the EQ predicate on the "price_type" field.
func PriceTypeEQ(v enum.PriceType) predicate.PriceHistory {
	vc := v
	return predicate.PriceHistory(sql.FieldEQ(FieldPriceType, vc))
}

// PriceTypeNEQ applies the NEQ predicate on the "price_type" field.
func PriceTypeNEQ(v enum.PriceType) predicate.PriceHistory {
	vc := v
	return predicate.PriceHistory(sql.FieldNEQ(FieldPriceType, vc))
}

// PriceTypeIn applies the In predicate on the "price_type" field.
func PriceTypeIn(vs ...enum.PriceType) predicate.PriceHistory {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PriceHistory(sql.FieldIn(FieldPriceType, v...))
}

// PriceTypeNotIn applies the NotIn predicate on the "price_type" field.
func PriceTypeNotIn(vs ...enum.PriceType) predicate.PriceHistory {
	v := make([]any, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PriceHistory(sql.FieldNotIn(FieldPriceType, v...))
}

// OldPriceEQ applies the EQ predicate on the "old_price" field.
func OldPriceEQ(v decimal.Decimal) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldEQ(FieldOldPrice, v))
}

// OldPriceNEQ applies the NEQ predicate on the "old_price" field.
func OldPriceNEQ(v decimal.Decimal) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldNEQ(FieldOldPrice, v))
}

// OldPriceIn applies the In predicate on the "old_price" field.
func OldPriceIn(vs ...decimal.Decimal) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldIn(FieldOldPrice, vs...))
}

// OldPriceNotIn applies the NotIn predicate on the "old_price" field.
func OldPriceNotIn(vs ...decimal.Decimal) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldNotIn(FieldOldPrice, vs...))
}

// OldPriceGT applies the GT predicate on the "old_price" field.
func OldPriceGT(v decimal.Decimal) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldGT(FieldOldPrice, v))
}

// OldPriceGTE applies the GTE predicate on the "old_price" field.
func OldPriceGTE(v decimal.Decimal) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldGTE(FieldOldPrice, v))
}

// OldPriceLT applies the LT predicate on the "old_price" field.
func OldPriceLT(v decimal.Decimal) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldLT(FieldOldPrice, v))
}

// OldPriceLTE applies the LTE predicate on the "old_price" field.
func OldPriceLTE(v decimal.Decimal) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldLTE(FieldOldPrice, v))
}

// NewPriceEQ applies the EQ predicate on the "new_price" field.
func NewPriceEQ(v decimal.Decimal) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldEQ(FieldNewPrice, v))
}

// NewPriceNEQ applies the NEQ predicate on the "new_price" field.
func NewPriceNEQ(v decimal.Decimal) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldNEQ(FieldNewPrice, v))
}

// NewPriceIn applies the In predicate on the "new_price" field.
func NewPriceIn(vs ...decimal.Decimal) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldIn(FieldNewPrice, vs...))
}

// NewPriceNotIn applies the NotIn predicate on the "new_price" field.
func NewPriceNotIn(vs ...decimal.Decimal) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldNotIn(FieldNewPrice, vs...))
}

// NewPriceGT applies the GT predicate on the "new_price" field.
func NewPriceGT(v decimal.Decimal) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldGT(FieldNewPrice, v))
}

// NewPriceGTE applies the GTE predicate on the "new_price" field.
func NewPriceGTE(v decimal.Decimal) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldGTE(FieldNewPrice, v))
}

// NewPriceLT applies the LT predicate on the "new_price" field.
func NewPriceLT(v decimal.Decimal) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldLT(FieldNewPrice, v))
}

// NewPriceLTE applies the LTE predicate on the "new_price" field.
func NewPriceLTE(v decimal.Decimal) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldLTE(FieldNewPrice, v))
}

// ChangedByEQ applies the EQ predicate on the "changed_by" field.
func ChangedByEQ(v int64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldEQ(FieldChangedBy, v))
}

// ChangedByNEQ applies the NEQ predicate on the "changed_by" field.
func ChangedByNEQ(v int64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldNEQ(FieldChangedBy, v))
}

// ChangedByIn applies the In predicate on the "changed_by" field.
func ChangedByIn(vs ...int64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldIn(FieldChangedBy, vs...))
}

// ChangedByNotIn applies the NotIn predicate on the "changed_by" field.
func ChangedByNotIn(vs ...int64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldNotIn(FieldChangedBy, vs...))
}

// ChangedByGT applies the GT predicate on the "changed_by" field.
func ChangedByGT(v int64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldGT(FieldChangedBy, v))
}

// ChangedByGTE applies the GTE predicate on the "changed_by" field.
func ChangedByGTE(v int64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldGTE(FieldChangedBy, v))
}

// ChangedByLT applies the LT predicate on the "changed_by" field.
func ChangedByLT(v int64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldLT(FieldChangedBy, v))
}

// ChangedByLTE applies the LTE predicate on the "changed_by" field.
func ChangedByLTE(v int64) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldLTE(FieldChangedBy, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldContainsFold(FieldReason, v))
}

// ChangedAtEQ applies the EQ predicate on the "changed_at" field.
func ChangedAtEQ(v time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldEQ(FieldChangedAt, v))
}

// ChangedAtNEQ applies the NEQ predicate on the "changed_at" field.
func ChangedAtNEQ(v time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldNEQ(FieldChangedAt, v))
}

// ChangedAtIn applies the In predicate on the "changed_at" field.
func ChangedAtIn(vs ...time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldIn(FieldChangedAt, vs...))
}

// ChangedAtNotIn applies the NotIn predicate on the "changed_at" field.
func ChangedAtNotIn(vs ...time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldNotIn(FieldChangedAt, vs...))
}

// ChangedAtGT applies the GT predicate on the "changed_at" field.
func ChangedAtGT(v time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldGT(FieldChangedAt, v))
}

// ChangedAtGTE applies the GTE predicate on the "changed_at" field.
func ChangedAtGTE(v time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldGTE(FieldChangedAt, v))
}

// ChangedAtLT applies the LT predicate on the "changed_at" field.
func ChangedAtLT(v time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldLT(FieldChangedAt, v))
}

// ChangedAtLTE applies the LTE predicate on the "changed_at" field.
func ChangedAtLTE(v time.Time) predicate.PriceHistory {
	return predicate.PriceHistory(sql.FieldLTE(FieldChangedAt, v))
}

// HasProduct applies the HasEdge predicate on the "product" edge.
func HasProduct() predicate.PriceHistory {
	return predicate.PriceHistory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProductTable, ProductColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProductWith applies the HasEdge predicate on the "product" edge with a given conditions (other predicates).
func HasProductWith(preds ...predicate.Product) predicate.PriceHistory {
	return predicate.PriceHistory(func(s *sql.Selector) {
		step := newProductStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PriceHistory) predicate.PriceHistory {
	return predicate.PriceHistory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PriceHistory) predicate.PriceHistory {
	return predicate.PriceHistory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PriceHistory) predicate.PriceHistory {
	return predicate.PriceHistory(sql.NotPredicates(p))
}
