// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/products/ent/barcode"
	"gitlab.calendaria.team/services/products/ent/enum"
	"gitlab.calendaria.team/services/products/ent/predicate"
	"gitlab.calendaria.team/services/products/ent/product"
)

// BarcodeUpdate is the builder for updating Barcode entities.
type BarcodeUpdate struct {
	config
	hooks     []Hook
	mutation  *BarcodeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the BarcodeUpdate builder.
func (bu *BarcodeUpdate) Where(ps ...predicate.Barcode) *BarcodeUpdate {
	bu.mutation.Where(ps...)
	return bu
}

// SetUpdatedAt sets the "updated_at" field.
func (bu *BarcodeUpdate) SetUpdatedAt(t time.Time) *BarcodeUpdate {
	bu.mutation.SetUpdatedAt(t)
	return bu
}

// SetProductID sets the "product_id" field.
func (bu *BarcodeUpdate) SetProductID(i int64) *BarcodeUpdate {
	bu.mutation.SetProductID(i)
	return bu
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (bu *BarcodeUpdate) SetNillableProductID(i *int64) *BarcodeUpdate {
	if i != nil {
		bu.SetProductID(*i)
	}
	return bu
}

// SetValue sets the "value" field.
func (bu *BarcodeUpdate) SetValue(s string) *BarcodeUpdate {
	bu.mutation.SetValue(s)
	return bu
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (bu *BarcodeUpdate) SetNillableValue(s *string) *BarcodeUpdate {
	if s != nil {
		bu.SetValue(*s)
	}
	return bu
}

// SetType sets the "type" field.
func (bu *BarcodeUpdate) SetType(et enum.BarcodeType) *BarcodeUpdate {
	bu.mutation.SetType(et)
	return bu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (bu *BarcodeUpdate) SetNillableType(et *enum.BarcodeType) *BarcodeUpdate {
	if et != nil {
		bu.SetType(*et)
	}
	return bu
}

// SetProduct sets the "product" edge to the Product entity.
func (bu *BarcodeUpdate) SetProduct(p *Product) *BarcodeUpdate {
	return bu.SetProductID(p.ID)
}

// Mutation returns the BarcodeMutation object of the builder.
func (bu *BarcodeUpdate) Mutation() *BarcodeMutation {
	return bu.mutation
}

// ClearProduct clears the "product" edge to the Product entity.
func (bu *BarcodeUpdate) ClearProduct() *BarcodeUpdate {
	bu.mutation.ClearProduct()
	return bu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (bu *BarcodeUpdate) Save(ctx context.Context) (int, error) {
	bu.defaults()
	return withHooks(ctx, bu.sqlSave, bu.mutation, bu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (bu *BarcodeUpdate) SaveX(ctx context.Context) int {
	affected, err := bu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bu *BarcodeUpdate) Exec(ctx context.Context) error {
	_, err := bu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bu *BarcodeUpdate) ExecX(ctx context.Context) {
	if err := bu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bu *BarcodeUpdate) defaults() {
	if _, ok := bu.mutation.UpdatedAt(); !ok {
		v := barcode.UpdateDefaultUpdatedAt()
		bu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bu *BarcodeUpdate) check() error {
	if v, ok := bu.mutation.Value(); ok {
		if err := barcode.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "Barcode.value": %w`, err)}
		}
	}
	if v, ok := bu.mutation.GetType(); ok {
		if err := barcode.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Barcode.type": %w`, err)}
		}
	}
	if bu.mutation.ProductCleared() && len(bu.mutation.ProductIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Barcode.product"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (bu *BarcodeUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *BarcodeUpdate {
	bu.modifiers = append(bu.modifiers, modifiers...)
	return bu
}

func (bu *BarcodeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := bu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(barcode.Table, barcode.Columns, sqlgraph.NewFieldSpec(barcode.FieldID, field.TypeInt64))
	if ps := bu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bu.mutation.UpdatedAt(); ok {
		_spec.SetField(barcode.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := bu.mutation.Value(); ok {
		_spec.SetField(barcode.FieldValue, field.TypeString, value)
	}
	if value, ok := bu.mutation.GetType(); ok {
		_spec.SetField(barcode.FieldType, field.TypeEnum, value)
	}
	if bu.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   barcode.ProductTable,
			Columns: []string{barcode.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := bu.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   barcode.ProductTable,
			Columns: []string{barcode.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(bu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, bu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{barcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	bu.mutation.done = true
	return n, nil
}

// BarcodeUpdateOne is the builder for updating a single Barcode entity.
type BarcodeUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *BarcodeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (buo *BarcodeUpdateOne) SetUpdatedAt(t time.Time) *BarcodeUpdateOne {
	buo.mutation.SetUpdatedAt(t)
	return buo
}

// SetProductID sets the "product_id" field.
func (buo *BarcodeUpdateOne) SetProductID(i int64) *BarcodeUpdateOne {
	buo.mutation.SetProductID(i)
	return buo
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (buo *BarcodeUpdateOne) SetNillableProductID(i *int64) *BarcodeUpdateOne {
	if i != nil {
		buo.SetProductID(*i)
	}
	return buo
}

// SetValue sets the "value" field.
func (buo *BarcodeUpdateOne) SetValue(s string) *BarcodeUpdateOne {
	buo.mutation.SetValue(s)
	return buo
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (buo *BarcodeUpdateOne) SetNillableValue(s *string) *BarcodeUpdateOne {
	if s != nil {
		buo.SetValue(*s)
	}
	return buo
}

// SetType sets the "type" field.
func (buo *BarcodeUpdateOne) SetType(et enum.BarcodeType) *BarcodeUpdateOne {
	buo.mutation.SetType(et)
	return buo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (buo *BarcodeUpdateOne) SetNillableType(et *enum.BarcodeType) *BarcodeUpdateOne {
	if et != nil {
		buo.SetType(*et)
	}
	return buo
}

// SetProduct sets the "product" edge to the Product entity.
func (buo *BarcodeUpdateOne) SetProduct(p *Product) *BarcodeUpdateOne {
	return buo.SetProductID(p.ID)
}

// Mutation returns the BarcodeMutation object of the builder.
func (buo *BarcodeUpdateOne) Mutation() *BarcodeMutation {
	return buo.mutation
}

// ClearProduct clears the "product" edge to the Product entity.
func (buo *BarcodeUpdateOne) ClearProduct() *BarcodeUpdateOne {
	buo.mutation.ClearProduct()
	return buo
}

// Where appends a list predicates to the BarcodeUpdate builder.
func (buo *BarcodeUpdateOne) Where(ps ...predicate.Barcode) *BarcodeUpdateOne {
	buo.mutation.Where(ps...)
	return buo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (buo *BarcodeUpdateOne) Select(field string, fields ...string) *BarcodeUpdateOne {
	buo.fields = append([]string{field}, fields...)
	return buo
}

// Save executes the query and returns the updated Barcode entity.
func (buo *BarcodeUpdateOne) Save(ctx context.Context) (*Barcode, error) {
	buo.defaults()
	return withHooks(ctx, buo.sqlSave, buo.mutation, buo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (buo *BarcodeUpdateOne) SaveX(ctx context.Context) *Barcode {
	node, err := buo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (buo *BarcodeUpdateOne) Exec(ctx context.Context) error {
	_, err := buo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (buo *BarcodeUpdateOne) ExecX(ctx context.Context) {
	if err := buo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (buo *BarcodeUpdateOne) defaults() {
	if _, ok := buo.mutation.UpdatedAt(); !ok {
		v := barcode.UpdateDefaultUpdatedAt()
		buo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (buo *BarcodeUpdateOne) check() error {
	if v, ok := buo.mutation.Value(); ok {
		if err := barcode.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "Barcode.value": %w`, err)}
		}
	}
	if v, ok := buo.mutation.GetType(); ok {
		if err := barcode.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Barcode.type": %w`, err)}
		}
	}
	if buo.mutation.ProductCleared() && len(buo.mutation.ProductIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Barcode.product"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (buo *BarcodeUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *BarcodeUpdateOne {
	buo.modifiers = append(buo.modifiers, modifiers...)
	return buo
}

func (buo *BarcodeUpdateOne) sqlSave(ctx context.Context) (_node *Barcode, err error) {
	if err := buo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(barcode.Table, barcode.Columns, sqlgraph.NewFieldSpec(barcode.FieldID, field.TypeInt64))
	id, ok := buo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Barcode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := buo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, barcode.FieldID)
		for _, f := range fields {
			if !barcode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != barcode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := buo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := buo.mutation.UpdatedAt(); ok {
		_spec.SetField(barcode.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := buo.mutation.Value(); ok {
		_spec.SetField(barcode.FieldValue, field.TypeString, value)
	}
	if value, ok := buo.mutation.GetType(); ok {
		_spec.SetField(barcode.FieldType, field.TypeEnum, value)
	}
	if buo.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   barcode.ProductTable,
			Columns: []string{barcode.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := buo.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   barcode.ProductTable,
			Columns: []string{barcode.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(buo.modifiers...)
	_node = &Barcode{config: buo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, buo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{barcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	buo.mutation.done = true
	return _node, nil
}
