// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/makesalekz/products/ent/barcode"
	"github.com/makesalekz/products/ent/enum"
	"github.com/makesalekz/products/ent/product"
)

// BarcodeCreate is the builder for creating a Barcode entity.
type BarcodeCreate struct {
	config
	mutation *BarcodeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (bc *BarcodeCreate) SetCreatedAt(t time.Time) *BarcodeCreate {
	bc.mutation.SetCreatedAt(t)
	return bc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (bc *BarcodeCreate) SetNillableCreatedAt(t *time.Time) *BarcodeCreate {
	if t != nil {
		bc.SetCreatedAt(*t)
	}
	return bc
}

// SetUpdatedAt sets the "updated_at" field.
func (bc *BarcodeCreate) SetUpdatedAt(t time.Time) *BarcodeCreate {
	bc.mutation.SetUpdatedAt(t)
	return bc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (bc *BarcodeCreate) SetNillableUpdatedAt(t *time.Time) *BarcodeCreate {
	if t != nil {
		bc.SetUpdatedAt(*t)
	}
	return bc
}

// SetTenantID sets the "tenant_id" field.
func (bc *BarcodeCreate) SetTenantID(i int64) *BarcodeCreate {
	bc.mutation.SetTenantID(i)
	return bc
}

// SetProductID sets the "product_id" field.
func (bc *BarcodeCreate) SetProductID(i int64) *BarcodeCreate {
	bc.mutation.SetProductID(i)
	return bc
}

// SetValue sets the "value" field.
func (bc *BarcodeCreate) SetValue(s string) *BarcodeCreate {
	bc.mutation.SetValue(s)
	return bc
}

// SetType sets the "type" field.
func (bc *BarcodeCreate) SetType(et enum.BarcodeType) *BarcodeCreate {
	bc.mutation.SetType(et)
	return bc
}

// SetNillableType sets the "type" field if the given value is not nil.
func (bc *BarcodeCreate) SetNillableType(et *enum.BarcodeType) *BarcodeCreate {
	if et != nil {
		bc.SetType(*et)
	}
	return bc
}

// SetID sets the "id" field.
func (bc *BarcodeCreate) SetID(i int64) *BarcodeCreate {
	bc.mutation.SetID(i)
	return bc
}

// SetProduct sets the "product" edge to the Product entity.
func (bc *BarcodeCreate) SetProduct(p *Product) *BarcodeCreate {
	return bc.SetProductID(p.ID)
}

// Mutation returns the BarcodeMutation object of the builder.
func (bc *BarcodeCreate) Mutation() *BarcodeMutation {
	return bc.mutation
}

// Save creates the Barcode in the database.
func (bc *BarcodeCreate) Save(ctx context.Context) (*Barcode, error) {
	bc.defaults()
	return withHooks(ctx, bc.sqlSave, bc.mutation, bc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (bc *BarcodeCreate) SaveX(ctx context.Context) *Barcode {
	v, err := bc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bc *BarcodeCreate) Exec(ctx context.Context) error {
	_, err := bc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bc *BarcodeCreate) ExecX(ctx context.Context) {
	if err := bc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bc *BarcodeCreate) defaults() {
	if _, ok := bc.mutation.CreatedAt(); !ok {
		v := barcode.DefaultCreatedAt()
		bc.mutation.SetCreatedAt(v)
	}
	if _, ok := bc.mutation.UpdatedAt(); !ok {
		v := barcode.DefaultUpdatedAt()
		bc.mutation.SetUpdatedAt(v)
	}
	if _, ok := bc.mutation.GetType(); !ok {
		v := barcode.DefaultType
		bc.mutation.SetType(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bc *BarcodeCreate) check() error {
	if _, ok := bc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Barcode.created_at"`)}
	}
	if _, ok := bc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Barcode.updated_at"`)}
	}
	if _, ok := bc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Barcode.tenant_id"`)}
	}
	if _, ok := bc.mutation.ProductID(); !ok {
		return &ValidationError{Name: "product_id", err: errors.New(`ent: missing required field "Barcode.product_id"`)}
	}
	if _, ok := bc.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "Barcode.value"`)}
	}
	if v, ok := bc.mutation.Value(); ok {
		if err := barcode.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "Barcode.value": %w`, err)}
		}
	}
	if _, ok := bc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Barcode.type"`)}
	}
	if v, ok := bc.mutation.GetType(); ok {
		if err := barcode.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Barcode.type": %w`, err)}
		}
	}
	if len(bc.mutation.ProductIDs()) == 0 {
		return &ValidationError{Name: "product", err: errors.New(`ent: missing required edge "Barcode.product"`)}
	}
	return nil
}

func (bc *BarcodeCreate) sqlSave(ctx context.Context) (*Barcode, error) {
	if err := bc.check(); err != nil {
		return nil, err
	}
	_node, _spec := bc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	bc.mutation.id = &_node.ID
	bc.mutation.done = true
	return _node, nil
}

func (bc *BarcodeCreate) createSpec() (*Barcode, *sqlgraph.CreateSpec) {
	var (
		_node = &Barcode{config: bc.config}
		_spec = sqlgraph.NewCreateSpec(barcode.Table, sqlgraph.NewFieldSpec(barcode.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = bc.conflict
	if id, ok := bc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := bc.mutation.CreatedAt(); ok {
		_spec.SetField(barcode.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := bc.mutation.UpdatedAt(); ok {
		_spec.SetField(barcode.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := bc.mutation.TenantID(); ok {
		_spec.SetField(barcode.FieldTenantID, field.TypeInt64, value)
		_node.TenantID = value
	}
	if value, ok := bc.mutation.Value(); ok {
		_spec.SetField(barcode.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := bc.mutation.GetType(); ok {
		_spec.SetField(barcode.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if nodes := bc.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   barcode.ProductTable,
			Columns: []string{barcode.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProductID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Barcode.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BarcodeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (bc *BarcodeCreate) OnConflict(opts ...sql.ConflictOption) *BarcodeUpsertOne {
	bc.conflict = opts
	return &BarcodeUpsertOne{
		create: bc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Barcode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (bc *BarcodeCreate) OnConflictColumns(columns ...string) *BarcodeUpsertOne {
	bc.conflict = append(bc.conflict, sql.ConflictColumns(columns...))
	return &BarcodeUpsertOne{
		create: bc,
	}
}

type (
	// BarcodeUpsertOne is the builder for "upsert"-ing
	//  one Barcode node.
	BarcodeUpsertOne struct {
		create *BarcodeCreate
	}

	// BarcodeUpsert is the "OnConflict" setter.
	BarcodeUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *BarcodeUpsert) SetUpdatedAt(v time.Time) *BarcodeUpsert {
	u.Set(barcode.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BarcodeUpsert) UpdateUpdatedAt() *BarcodeUpsert {
	u.SetExcluded(barcode.FieldUpdatedAt)
	return u
}

// SetProductID sets the "product_id" field.
func (u *BarcodeUpsert) SetProductID(v int64) *BarcodeUpsert {
	u.Set(barcode.FieldProductID, v)
	return u
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *BarcodeUpsert) UpdateProductID() *BarcodeUpsert {
	u.SetExcluded(barcode.FieldProductID)
	return u
}

// SetValue sets the "value" field.
func (u *BarcodeUpsert) SetValue(v string) *BarcodeUpsert {
	u.Set(barcode.FieldValue, v)
	return u
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *BarcodeUpsert) UpdateValue() *BarcodeUpsert {
	u.SetExcluded(barcode.FieldValue)
	return u
}

// SetType sets the "type" field.
func (u *BarcodeUpsert) SetType(v enum.BarcodeType) *BarcodeUpsert {
	u.Set(barcode.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *BarcodeUpsert) UpdateType() *BarcodeUpsert {
	u.SetExcluded(barcode.FieldType)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Barcode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(barcode.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BarcodeUpsertOne) UpdateNewValues() *BarcodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(barcode.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(barcode.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(barcode.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Barcode.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BarcodeUpsertOne) Ignore() *BarcodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BarcodeUpsertOne) DoNothing() *BarcodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BarcodeCreate.OnConflict
// documentation for more info.
func (u *BarcodeUpsertOne) Update(set func(*BarcodeUpsert)) *BarcodeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BarcodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BarcodeUpsertOne) SetUpdatedAt(v time.Time) *BarcodeUpsertOne {
	return u.Update(func(s *BarcodeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BarcodeUpsertOne) UpdateUpdatedAt() *BarcodeUpsertOne {
	return u.Update(func(s *BarcodeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetProductID sets the "product_id" field.
func (u *BarcodeUpsertOne) SetProductID(v int64) *BarcodeUpsertOne {
	return u.Update(func(s *BarcodeUpsert) {
		s.SetProductID(v)
	})
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *BarcodeUpsertOne) UpdateProductID() *BarcodeUpsertOne {
	return u.Update(func(s *BarcodeUpsert) {
		s.UpdateProductID()
	})
}

// SetValue sets the "value" field.
func (u *BarcodeUpsertOne) SetValue(v string) *BarcodeUpsertOne {
	return u.Update(func(s *BarcodeUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *BarcodeUpsertOne) UpdateValue() *BarcodeUpsertOne {
	return u.Update(func(s *BarcodeUpsert) {
		s.UpdateValue()
	})
}

// SetType sets the "type" field.
func (u *BarcodeUpsertOne) SetType(v enum.BarcodeType) *BarcodeUpsertOne {
	return u.Update(func(s *BarcodeUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *BarcodeUpsertOne) UpdateType() *BarcodeUpsertOne {
	return u.Update(func(s *BarcodeUpsert) {
		s.UpdateType()
	})
}

// Exec executes the query.
func (u *BarcodeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BarcodeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BarcodeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BarcodeUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BarcodeUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BarcodeCreateBulk is the builder for creating many Barcode entities in bulk.
type BarcodeCreateBulk struct {
	config
	err      error
	builders []*BarcodeCreate
	conflict []sql.ConflictOption
}

// Save creates the Barcode entities in the database.
func (bcb *BarcodeCreateBulk) Save(ctx context.Context) ([]*Barcode, error) {
	if bcb.err != nil {
		return nil, bcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(bcb.builders))
	nodes := make([]*Barcode, len(bcb.builders))
	mutators := make([]Mutator, len(bcb.builders))
	for i := range bcb.builders {
		func(i int, root context.Context) {
			builder := bcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BarcodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = bcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bcb *BarcodeCreateBulk) SaveX(ctx context.Context) []*Barcode {
	v, err := bcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bcb *BarcodeCreateBulk) Exec(ctx context.Context) error {
	_, err := bcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bcb *BarcodeCreateBulk) ExecX(ctx context.Context) {
	if err := bcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Barcode.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BarcodeUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (bcb *BarcodeCreateBulk) OnConflict(opts ...sql.ConflictOption) *BarcodeUpsertBulk {
	bcb.conflict = opts
	return &BarcodeUpsertBulk{
		create: bcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Barcode.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (bcb *BarcodeCreateBulk) OnConflictColumns(columns ...string) *BarcodeUpsertBulk {
	bcb.conflict = append(bcb.conflict, sql.ConflictColumns(columns...))
	return &BarcodeUpsertBulk{
		create: bcb,
	}
}

// BarcodeUpsertBulk is the builder for "upsert"-ing
// a bulk of Barcode nodes.
type BarcodeUpsertBulk struct {
	create *BarcodeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Barcode.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(barcode.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BarcodeUpsertBulk) UpdateNewValues() *BarcodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(barcode.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(barcode.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(barcode.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Barcode.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BarcodeUpsertBulk) Ignore() *BarcodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BarcodeUpsertBulk) DoNothing() *BarcodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BarcodeCreateBulk.OnConflict
// documentation for more info.
func (u *BarcodeUpsertBulk) Update(set func(*BarcodeUpsert)) *BarcodeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BarcodeUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BarcodeUpsertBulk) SetUpdatedAt(v time.Time) *BarcodeUpsertBulk {
	return u.Update(func(s *BarcodeUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BarcodeUpsertBulk) UpdateUpdatedAt() *BarcodeUpsertBulk {
	return u.Update(func(s *BarcodeUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetProductID sets the "product_id" field.
func (u *BarcodeUpsertBulk) SetProductID(v int64) *BarcodeUpsertBulk {
	return u.Update(func(s *BarcodeUpsert) {
		s.SetProductID(v)
	})
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *BarcodeUpsertBulk) UpdateProductID() *BarcodeUpsertBulk {
	return u.Update(func(s *BarcodeUpsert) {
		s.UpdateProductID()
	})
}

// SetValue sets the "value" field.
func (u *BarcodeUpsertBulk) SetValue(v string) *BarcodeUpsertBulk {
	return u.Update(func(s *BarcodeUpsert) {
		s.SetValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *BarcodeUpsertBulk) UpdateValue() *BarcodeUpsertBulk {
	return u.Update(func(s *BarcodeUpsert) {
		s.UpdateValue()
	})
}

// SetType sets the "type" field.
func (u *BarcodeUpsertBulk) SetType(v enum.BarcodeType) *BarcodeUpsertBulk {
	return u.Update(func(s *BarcodeUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *BarcodeUpsertBulk) UpdateType() *BarcodeUpsertBulk {
	return u.Update(func(s *BarcodeUpsert) {
		s.UpdateType()
	})
}

// Exec executes the query.
func (u *BarcodeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BarcodeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BarcodeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BarcodeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
