// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/products/ent/barcode"
	"gitlab.calendaria.team/services/products/ent/predicate"
	"gitlab.calendaria.team/services/products/ent/product"
)

// BarcodeQuery is the builder for querying Barcode entities.
type BarcodeQuery struct {
	config
	ctx         *QueryContext
	order       []barcode.OrderOption
	inters      []Interceptor
	predicates  []predicate.Barcode
	withProduct *ProductQuery
	modifiers   []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the BarcodeQuery builder.
func (bq *BarcodeQuery) Where(ps ...predicate.Barcode) *BarcodeQuery {
	bq.predicates = append(bq.predicates, ps...)
	return bq
}

// Limit the number of records to be returned by this query.
func (bq *BarcodeQuery) Limit(limit int) *BarcodeQuery {
	bq.ctx.Limit = &limit
	return bq
}

// Offset to start from.
func (bq *BarcodeQuery) Offset(offset int) *BarcodeQuery {
	bq.ctx.Offset = &offset
	return bq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (bq *BarcodeQuery) Unique(unique bool) *BarcodeQuery {
	bq.ctx.Unique = &unique
	return bq
}

// Order specifies how the records should be ordered.
func (bq *BarcodeQuery) Order(o ...barcode.OrderOption) *BarcodeQuery {
	bq.order = append(bq.order, o...)
	return bq
}

// QueryProduct chains the current query on the "product" edge.
func (bq *BarcodeQuery) QueryProduct() *ProductQuery {
	query := (&ProductClient{config: bq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := bq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := bq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(barcode.Table, barcode.FieldID, selector),
			sqlgraph.To(product.Table, product.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, barcode.ProductTable, barcode.ProductColumn),
		)
		fromU = sqlgraph.SetNeighbors(bq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Barcode entity from the query.
// Returns a *NotFoundError when no Barcode was found.
func (bq *BarcodeQuery) First(ctx context.Context) (*Barcode, error) {
	nodes, err := bq.Limit(1).All(setContextOp(ctx, bq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{barcode.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (bq *BarcodeQuery) FirstX(ctx context.Context) *Barcode {
	node, err := bq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Barcode ID from the query.
// Returns a *NotFoundError when no Barcode ID was found.
func (bq *BarcodeQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = bq.Limit(1).IDs(setContextOp(ctx, bq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{barcode.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (bq *BarcodeQuery) FirstIDX(ctx context.Context) int64 {
	id, err := bq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Barcode entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Barcode entity is found.
// Returns a *NotFoundError when no Barcode entities are found.
func (bq *BarcodeQuery) Only(ctx context.Context) (*Barcode, error) {
	nodes, err := bq.Limit(2).All(setContextOp(ctx, bq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{barcode.Label}
	default:
		return nil, &NotSingularError{barcode.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (bq *BarcodeQuery) OnlyX(ctx context.Context) *Barcode {
	node, err := bq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Barcode ID in the query.
// Returns a *NotSingularError when more than one Barcode ID is found.
// Returns a *NotFoundError when no entities are found.
func (bq *BarcodeQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = bq.Limit(2).IDs(setContextOp(ctx, bq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{barcode.Label}
	default:
		err = &NotSingularError{barcode.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (bq *BarcodeQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := bq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Barcodes.
func (bq *BarcodeQuery) All(ctx context.Context) ([]*Barcode, error) {
	ctx = setContextOp(ctx, bq.ctx, ent.OpQueryAll)
	if err := bq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Barcode, *BarcodeQuery]()
	return withInterceptors[[]*Barcode](ctx, bq, qr, bq.inters)
}

// AllX is like All, but panics if an error occurs.
func (bq *BarcodeQuery) AllX(ctx context.Context) []*Barcode {
	nodes, err := bq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Barcode IDs.
func (bq *BarcodeQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if bq.ctx.Unique == nil && bq.path != nil {
		bq.Unique(true)
	}
	ctx = setContextOp(ctx, bq.ctx, ent.OpQueryIDs)
	if err = bq.Select(barcode.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (bq *BarcodeQuery) IDsX(ctx context.Context) []int64 {
	ids, err := bq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (bq *BarcodeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, bq.ctx, ent.OpQueryCount)
	if err := bq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, bq, querierCount[*BarcodeQuery](), bq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (bq *BarcodeQuery) CountX(ctx context.Context) int {
	count, err := bq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (bq *BarcodeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, bq.ctx, ent.OpQueryExist)
	switch _, err := bq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (bq *BarcodeQuery) ExistX(ctx context.Context) bool {
	exist, err := bq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the BarcodeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (bq *BarcodeQuery) Clone() *BarcodeQuery {
	if bq == nil {
		return nil
	}
	return &BarcodeQuery{
		config:      bq.config,
		ctx:         bq.ctx.Clone(),
		order:       append([]barcode.OrderOption{}, bq.order...),
		inters:      append([]Interceptor{}, bq.inters...),
		predicates:  append([]predicate.Barcode{}, bq.predicates...),
		withProduct: bq.withProduct.Clone(),
		// clone intermediate query.
		sql:  bq.sql.Clone(),
		path: bq.path,
	}
}

// WithProduct tells the query-builder to eager-load the nodes that are connected to
// the "product" edge. The optional arguments are used to configure the query builder of the edge.
func (bq *BarcodeQuery) WithProduct(opts ...func(*ProductQuery)) *BarcodeQuery {
	query := (&ProductClient{config: bq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	bq.withProduct = query
	return bq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Barcode.Query().
//		GroupBy(barcode.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (bq *BarcodeQuery) GroupBy(field string, fields ...string) *BarcodeGroupBy {
	bq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &BarcodeGroupBy{build: bq}
	grbuild.flds = &bq.ctx.Fields
	grbuild.label = barcode.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Barcode.Query().
//		Select(barcode.FieldCreatedAt).
//		Scan(ctx, &v)
func (bq *BarcodeQuery) Select(fields ...string) *BarcodeSelect {
	bq.ctx.Fields = append(bq.ctx.Fields, fields...)
	sbuild := &BarcodeSelect{BarcodeQuery: bq}
	sbuild.label = barcode.Label
	sbuild.flds, sbuild.scan = &bq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a BarcodeSelect configured with the given aggregations.
func (bq *BarcodeQuery) Aggregate(fns ...AggregateFunc) *BarcodeSelect {
	return bq.Select().Aggregate(fns...)
}

func (bq *BarcodeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range bq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, bq); err != nil {
				return err
			}
		}
	}
	for _, f := range bq.ctx.Fields {
		if !barcode.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if bq.path != nil {
		prev, err := bq.path(ctx)
		if err != nil {
			return err
		}
		bq.sql = prev
	}
	return nil
}

func (bq *BarcodeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Barcode, error) {
	var (
		nodes       = []*Barcode{}
		_spec       = bq.querySpec()
		loadedTypes = [1]bool{
			bq.withProduct != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Barcode).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Barcode{config: bq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(bq.modifiers) > 0 {
		_spec.Modifiers = bq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, bq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := bq.withProduct; query != nil {
		if err := bq.loadProduct(ctx, query, nodes, nil,
			func(n *Barcode, e *Product) { n.Edges.Product = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (bq *BarcodeQuery) loadProduct(ctx context.Context, query *ProductQuery, nodes []*Barcode, init func(*Barcode), assign func(*Barcode, *Product)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*Barcode)
	for i := range nodes {
		fk := nodes[i].ProductID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(product.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "product_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (bq *BarcodeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := bq.querySpec()
	if len(bq.modifiers) > 0 {
		_spec.Modifiers = bq.modifiers
	}
	_spec.Node.Columns = bq.ctx.Fields
	if len(bq.ctx.Fields) > 0 {
		_spec.Unique = bq.ctx.Unique != nil && *bq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, bq.driver, _spec)
}

func (bq *BarcodeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(barcode.Table, barcode.Columns, sqlgraph.NewFieldSpec(barcode.FieldID, field.TypeInt64))
	_spec.From = bq.sql
	if unique := bq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if bq.path != nil {
		_spec.Unique = true
	}
	if fields := bq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, barcode.FieldID)
		for i := range fields {
			if fields[i] != barcode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if bq.withProduct != nil {
			_spec.Node.AddColumnOnce(barcode.FieldProductID)
		}
	}
	if ps := bq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := bq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := bq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := bq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (bq *BarcodeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(bq.driver.Dialect())
	t1 := builder.Table(barcode.Table)
	columns := bq.ctx.Fields
	if len(columns) == 0 {
		columns = barcode.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if bq.sql != nil {
		selector = bq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if bq.ctx.Unique != nil && *bq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range bq.modifiers {
		m(selector)
	}
	for _, p := range bq.predicates {
		p(selector)
	}
	for _, p := range bq.order {
		p(selector)
	}
	if offset := bq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := bq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (bq *BarcodeQuery) Modify(modifiers ...func(s *sql.Selector)) *BarcodeSelect {
	bq.modifiers = append(bq.modifiers, modifiers...)
	return bq.Select()
}

// BarcodeGroupBy is the group-by builder for Barcode entities.
type BarcodeGroupBy struct {
	selector
	build *BarcodeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (bgb *BarcodeGroupBy) Aggregate(fns ...AggregateFunc) *BarcodeGroupBy {
	bgb.fns = append(bgb.fns, fns...)
	return bgb
}

// Scan applies the selector query and scans the result into the given value.
func (bgb *BarcodeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bgb.build.ctx, ent.OpQueryGroupBy)
	if err := bgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BarcodeQuery, *BarcodeGroupBy](ctx, bgb.build, bgb, bgb.build.inters, v)
}

func (bgb *BarcodeGroupBy) sqlScan(ctx context.Context, root *BarcodeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(bgb.fns))
	for _, fn := range bgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*bgb.flds)+len(bgb.fns))
		for _, f := range *bgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*bgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// BarcodeSelect is the builder for selecting fields of Barcode entities.
type BarcodeSelect struct {
	*BarcodeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (bs *BarcodeSelect) Aggregate(fns ...AggregateFunc) *BarcodeSelect {
	bs.fns = append(bs.fns, fns...)
	return bs
}

// Scan applies the selector query and scans the result into the given value.
func (bs *BarcodeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, bs.ctx, ent.OpQuerySelect)
	if err := bs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*BarcodeQuery, *BarcodeSelect](ctx, bs.BarcodeQuery, bs, bs.inters, v)
}

func (bs *BarcodeSelect) sqlScan(ctx context.Context, root *BarcodeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(bs.fns))
	for _, fn := range bs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*bs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := bs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (bs *BarcodeSelect) Modify(modifiers ...func(s *sql.Selector)) *BarcodeSelect {
	bs.modifiers = append(bs.modifiers, modifiers...)
	return bs
}
