// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/products/ent/predicate"
	"gitlab.calendaria.team/services/products/ent/pricehistory"
	"gitlab.calendaria.team/services/products/ent/product"
)

// PriceHistoryUpdate is the builder for updating PriceHistory entities.
type PriceHistoryUpdate struct {
	config
	hooks     []Hook
	mutation  *PriceHistoryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the PriceHistoryUpdate builder.
func (phu *PriceHistoryUpdate) Where(ps ...predicate.PriceHistory) *PriceHistoryUpdate {
	phu.mutation.Where(ps...)
	return phu
}

// SetUpdatedAt sets the "updated_at" field.
func (phu *PriceHistoryUpdate) SetUpdatedAt(t time.Time) *PriceHistoryUpdate {
	phu.mutation.SetUpdatedAt(t)
	return phu
}

// SetProductID sets the "product_id" field.
func (phu *PriceHistoryUpdate) SetProductID(i int64) *PriceHistoryUpdate {
	phu.mutation.SetProductID(i)
	return phu
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (phu *PriceHistoryUpdate) SetNillableProductID(i *int64) *PriceHistoryUpdate {
	if i != nil {
		phu.SetProductID(*i)
	}
	return phu
}

// SetReason sets the "reason" field.
func (phu *PriceHistoryUpdate) SetReason(s string) *PriceHistoryUpdate {
	phu.mutation.SetReason(s)
	return phu
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (phu *PriceHistoryUpdate) SetNillableReason(s *string) *PriceHistoryUpdate {
	if s != nil {
		phu.SetReason(*s)
	}
	return phu
}

// ClearReason clears the value of the "reason" field.
func (phu *PriceHistoryUpdate) ClearReason() *PriceHistoryUpdate {
	phu.mutation.ClearReason()
	return phu
}

// SetProduct sets the "product" edge to the Product entity.
func (phu *PriceHistoryUpdate) SetProduct(p *Product) *PriceHistoryUpdate {
	return phu.SetProductID(p.ID)
}

// Mutation returns the PriceHistoryMutation object of the builder.
func (phu *PriceHistoryUpdate) Mutation() *PriceHistoryMutation {
	return phu.mutation
}

// ClearProduct clears the "product" edge to the Product entity.
func (phu *PriceHistoryUpdate) ClearProduct() *PriceHistoryUpdate {
	phu.mutation.ClearProduct()
	return phu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (phu *PriceHistoryUpdate) Save(ctx context.Context) (int, error) {
	phu.defaults()
	return withHooks(ctx, phu.sqlSave, phu.mutation, phu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (phu *PriceHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := phu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (phu *PriceHistoryUpdate) Exec(ctx context.Context) error {
	_, err := phu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (phu *PriceHistoryUpdate) ExecX(ctx context.Context) {
	if err := phu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (phu *PriceHistoryUpdate) defaults() {
	if _, ok := phu.mutation.UpdatedAt(); !ok {
		v := pricehistory.UpdateDefaultUpdatedAt()
		phu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (phu *PriceHistoryUpdate) check() error {
	if phu.mutation.ProductCleared() && len(phu.mutation.ProductIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PriceHistory.product"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (phu *PriceHistoryUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PriceHistoryUpdate {
	phu.modifiers = append(phu.modifiers, modifiers...)
	return phu
}

func (phu *PriceHistoryUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := phu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(pricehistory.Table, pricehistory.Columns, sqlgraph.NewFieldSpec(pricehistory.FieldID, field.TypeInt64))
	if ps := phu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := phu.mutation.UpdatedAt(); ok {
		_spec.SetField(pricehistory.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := phu.mutation.Reason(); ok {
		_spec.SetField(pricehistory.FieldReason, field.TypeString, value)
	}
	if phu.mutation.ReasonCleared() {
		_spec.ClearField(pricehistory.FieldReason, field.TypeString)
	}
	if phu.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pricehistory.ProductTable,
			Columns: []string{pricehistory.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := phu.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pricehistory.ProductTable,
			Columns: []string{pricehistory.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(phu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, phu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pricehistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	phu.mutation.done = true
	return n, nil
}

// PriceHistoryUpdateOne is the builder for updating a single PriceHistory entity.
type PriceHistoryUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *PriceHistoryMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (phuo *PriceHistoryUpdateOne) SetUpdatedAt(t time.Time) *PriceHistoryUpdateOne {
	phuo.mutation.SetUpdatedAt(t)
	return phuo
}

// SetProductID sets the "product_id" field.
func (phuo *PriceHistoryUpdateOne) SetProductID(i int64) *PriceHistoryUpdateOne {
	phuo.mutation.SetProductID(i)
	return phuo
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (phuo *PriceHistoryUpdateOne) SetNillableProductID(i *int64) *PriceHistoryUpdateOne {
	if i != nil {
		phuo.SetProductID(*i)
	}
	return phuo
}

// SetReason sets the "reason" field.
func (phuo *PriceHistoryUpdateOne) SetReason(s string) *PriceHistoryUpdateOne {
	phuo.mutation.SetReason(s)
	return phuo
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (phuo *PriceHistoryUpdateOne) SetNillableReason(s *string) *PriceHistoryUpdateOne {
	if s != nil {
		phuo.SetReason(*s)
	}
	return phuo
}

// ClearReason clears the value of the "reason" field.
func (phuo *PriceHistoryUpdateOne) ClearReason() *PriceHistoryUpdateOne {
	phuo.mutation.ClearReason()
	return phuo
}

// SetProduct sets the "product" edge to the Product entity.
func (phuo *PriceHistoryUpdateOne) SetProduct(p *Product) *PriceHistoryUpdateOne {
	return phuo.SetProductID(p.ID)
}

// Mutation returns the PriceHistoryMutation object of the builder.
func (phuo *PriceHistoryUpdateOne) Mutation() *PriceHistoryMutation {
	return phuo.mutation
}

// ClearProduct clears the "product" edge to the Product entity.
func (phuo *PriceHistoryUpdateOne) ClearProduct() *PriceHistoryUpdateOne {
	phuo.mutation.ClearProduct()
	return phuo
}

// Where appends a list predicates to the PriceHistoryUpdate builder.
func (phuo *PriceHistoryUpdateOne) Where(ps ...predicate.PriceHistory) *PriceHistoryUpdateOne {
	phuo.mutation.Where(ps...)
	return phuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (phuo *PriceHistoryUpdateOne) Select(field string, fields ...string) *PriceHistoryUpdateOne {
	phuo.fields = append([]string{field}, fields...)
	return phuo
}

// Save executes the query and returns the updated PriceHistory entity.
func (phuo *PriceHistoryUpdateOne) Save(ctx context.Context) (*PriceHistory, error) {
	phuo.defaults()
	return withHooks(ctx, phuo.sqlSave, phuo.mutation, phuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (phuo *PriceHistoryUpdateOne) SaveX(ctx context.Context) *PriceHistory {
	node, err := phuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (phuo *PriceHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := phuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (phuo *PriceHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := phuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (phuo *PriceHistoryUpdateOne) defaults() {
	if _, ok := phuo.mutation.UpdatedAt(); !ok {
		v := pricehistory.UpdateDefaultUpdatedAt()
		phuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (phuo *PriceHistoryUpdateOne) check() error {
	if phuo.mutation.ProductCleared() && len(phuo.mutation.ProductIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PriceHistory.product"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (phuo *PriceHistoryUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PriceHistoryUpdateOne {
	phuo.modifiers = append(phuo.modifiers, modifiers...)
	return phuo
}

func (phuo *PriceHistoryUpdateOne) sqlSave(ctx context.Context) (_node *PriceHistory, err error) {
	if err := phuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pricehistory.Table, pricehistory.Columns, sqlgraph.NewFieldSpec(pricehistory.FieldID, field.TypeInt64))
	id, ok := phuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PriceHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := phuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pricehistory.FieldID)
		for _, f := range fields {
			if !pricehistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pricehistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := phuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := phuo.mutation.UpdatedAt(); ok {
		_spec.SetField(pricehistory.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := phuo.mutation.Reason(); ok {
		_spec.SetField(pricehistory.FieldReason, field.TypeString, value)
	}
	if phuo.mutation.ReasonCleared() {
		_spec.ClearField(pricehistory.FieldReason, field.TypeString)
	}
	if phuo.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pricehistory.ProductTable,
			Columns: []string{pricehistory.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := phuo.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pricehistory.ProductTable,
			Columns: []string{pricehistory.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(phuo.modifiers...)
	_node = &PriceHistory{config: phuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, phuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pricehistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	phuo.mutation.done = true
	return _node, nil
}
