// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/shopspring/decimal"
	"gitlab.calendaria.team/services/products/ent/enum"
	"gitlab.calendaria.team/services/products/ent/pricehistory"
	"gitlab.calendaria.team/services/products/ent/product"
)

// PriceHistory is the model entity for the PriceHistory schema.
type PriceHistory struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID int64 `json:"tenant_id,omitempty"`
	// ProductID holds the value of the "product_id" field.
	ProductID int64 `json:"product_id,omitempty"`
	// PriceType holds the value of the "price_type" field.
	PriceType enum.PriceType `json:"price_type,omitempty"`
	// OldPrice holds the value of the "old_price" field.
	OldPrice decimal.Decimal `json:"old_price,omitempty"`
	// NewPrice holds the value of the "new_price" field.
	NewPrice decimal.Decimal `json:"new_price,omitempty"`
	// ChangedBy holds the value of the "changed_by" field.
	ChangedBy int64 `json:"changed_by,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// ChangedAt holds the value of the "changed_at" field.
	ChangedAt time.Time `json:"changed_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PriceHistoryQuery when eager-loading is set.
	Edges        PriceHistoryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PriceHistoryEdges holds the relations/edges for other nodes in the graph.
type PriceHistoryEdges struct {
	// Product holds the value of the product edge.
	Product *Product `json:"product,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ProductOrErr returns the Product value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PriceHistoryEdges) ProductOrErr() (*Product, error) {
	if e.Product != nil {
		return e.Product, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: product.Label}
	}
	return nil, &NotLoadedError{edge: "product"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PriceHistory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pricehistory.FieldOldPrice, pricehistory.FieldNewPrice:
			values[i] = new(decimal.Decimal)
		case pricehistory.FieldID, pricehistory.FieldTenantID, pricehistory.FieldProductID, pricehistory.FieldChangedBy:
			values[i] = new(sql.NullInt64)
		case pricehistory.FieldPriceType, pricehistory.FieldReason:
			values[i] = new(sql.NullString)
		case pricehistory.FieldCreatedAt, pricehistory.FieldUpdatedAt, pricehistory.FieldChangedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PriceHistory fields.
func (ph *PriceHistory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pricehistory.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ph.ID = int64(value.Int64)
		case pricehistory.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ph.CreatedAt = value.Time
			}
		case pricehistory.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ph.UpdatedAt = value.Time
			}
		case pricehistory.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				ph.TenantID = value.Int64
			}
		case pricehistory.FieldProductID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field product_id", values[i])
			} else if value.Valid {
				ph.ProductID = value.Int64
			}
		case pricehistory.FieldPriceType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field price_type", values[i])
			} else if value.Valid {
				ph.PriceType = enum.PriceType(value.String)
			}
		case pricehistory.FieldOldPrice:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field old_price", values[i])
			} else if value != nil {
				ph.OldPrice = *value
			}
		case pricehistory.FieldNewPrice:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field new_price", values[i])
			} else if value != nil {
				ph.NewPrice = *value
			}
		case pricehistory.FieldChangedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field changed_by", values[i])
			} else if value.Valid {
				ph.ChangedBy = value.Int64
			}
		case pricehistory.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				ph.Reason = value.String
			}
		case pricehistory.FieldChangedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field changed_at", values[i])
			} else if value.Valid {
				ph.ChangedAt = value.Time
			}
		default:
			ph.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PriceHistory.
// This includes values selected through modifiers, order, etc.
func (ph *PriceHistory) Value(name string) (ent.Value, error) {
	return ph.selectValues.Get(name)
}

// QueryProduct queries the "product" edge of the PriceHistory entity.
func (ph *PriceHistory) QueryProduct() *ProductQuery {
	return NewPriceHistoryClient(ph.config).QueryProduct(ph)
}

// Update returns a builder for updating this PriceHistory.
// Note that you need to call PriceHistory.Unwrap() before calling this method if this PriceHistory
// was returned from a transaction, and the transaction was committed or rolled back.
func (ph *PriceHistory) Update() *PriceHistoryUpdateOne {
	return NewPriceHistoryClient(ph.config).UpdateOne(ph)
}

// Unwrap unwraps the PriceHistory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ph *PriceHistory) Unwrap() *PriceHistory {
	_tx, ok := ph.config.driver.(*txDriver)
	if !ok {
		panic("ent: PriceHistory is not a transactional entity")
	}
	ph.config.driver = _tx.drv
	return ph
}

// String implements the fmt.Stringer.
func (ph *PriceHistory) String() string {
	var builder strings.Builder
	builder.WriteString("PriceHistory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ph.ID))
	builder.WriteString("created_at=")
	builder.WriteString(ph.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ph.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", ph.TenantID))
	builder.WriteString(", ")
	builder.WriteString("product_id=")
	builder.WriteString(fmt.Sprintf("%v", ph.ProductID))
	builder.WriteString(", ")
	builder.WriteString("price_type=")
	builder.WriteString(fmt.Sprintf("%v", ph.PriceType))
	builder.WriteString(", ")
	builder.WriteString("old_price=")
	builder.WriteString(fmt.Sprintf("%v", ph.OldPrice))
	builder.WriteString(", ")
	builder.WriteString("new_price=")
	builder.WriteString(fmt.Sprintf("%v", ph.NewPrice))
	builder.WriteString(", ")
	builder.WriteString("changed_by=")
	builder.WriteString(fmt.Sprintf("%v", ph.ChangedBy))
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(ph.Reason)
	builder.WriteString(", ")
	builder.WriteString("changed_at=")
	builder.WriteString(ph.ChangedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PriceHistories is a parsable slice of PriceHistory.
type PriceHistories []*PriceHistory
