// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/makesalekz/products/ent/predicate"
	"github.com/makesalekz/products/ent/pricehistory"
)

// PriceHistoryDelete is the builder for deleting a PriceHistory entity.
type PriceHistoryDelete struct {
	config
	hooks    []Hook
	mutation *PriceHistoryMutation
}

// Where appends a list predicates to the PriceHistoryDelete builder.
func (phd *PriceHistoryDelete) Where(ps ...predicate.PriceHistory) *PriceHistoryDelete {
	phd.mutation.Where(ps...)
	return phd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (phd *PriceHistoryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, phd.sqlExec, phd.mutation, phd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (phd *PriceHistoryDelete) ExecX(ctx context.Context) int {
	n, err := phd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (phd *PriceHistoryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(pricehistory.Table, sqlgraph.NewFieldSpec(pricehistory.FieldID, field.TypeInt64))
	if ps := phd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, phd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	phd.mutation.done = true
	return affected, err
}

// PriceHistoryDeleteOne is the builder for deleting a single PriceHistory entity.
type PriceHistoryDeleteOne struct {
	phd *PriceHistoryDelete
}

// Where appends a list predicates to the PriceHistoryDelete builder.
func (phdo *PriceHistoryDeleteOne) Where(ps ...predicate.PriceHistory) *PriceHistoryDeleteOne {
	phdo.phd.mutation.Where(ps...)
	return phdo
}

// Exec executes the deletion query.
func (phdo *PriceHistoryDeleteOne) Exec(ctx context.Context) error {
	n, err := phdo.phd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{pricehistory.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (phdo *PriceHistoryDeleteOne) ExecX(ctx context.Context) {
	if err := phdo.Exec(ctx); err != nil {
		panic(err)
	}
}
