// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/makesalekz/products/ent/predicate"
	"github.com/makesalekz/products/ent/pricehistory"
	"github.com/makesalekz/products/ent/product"
)

// PriceHistoryQuery is the builder for querying PriceHistory entities.
type PriceHistoryQuery struct {
	config
	ctx         *QueryContext
	order       []pricehistory.OrderOption
	inters      []Interceptor
	predicates  []predicate.PriceHistory
	withProduct *ProductQuery
	modifiers   []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PriceHistoryQuery builder.
func (phq *PriceHistoryQuery) Where(ps ...predicate.PriceHistory) *PriceHistoryQuery {
	phq.predicates = append(phq.predicates, ps...)
	return phq
}

// Limit the number of records to be returned by this query.
func (phq *PriceHistoryQuery) Limit(limit int) *PriceHistoryQuery {
	phq.ctx.Limit = &limit
	return phq
}

// Offset to start from.
func (phq *PriceHistoryQuery) Offset(offset int) *PriceHistoryQuery {
	phq.ctx.Offset = &offset
	return phq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (phq *PriceHistoryQuery) Unique(unique bool) *PriceHistoryQuery {
	phq.ctx.Unique = &unique
	return phq
}

// Order specifies how the records should be ordered.
func (phq *PriceHistoryQuery) Order(o ...pricehistory.OrderOption) *PriceHistoryQuery {
	phq.order = append(phq.order, o...)
	return phq
}

// QueryProduct chains the current query on the "product" edge.
func (phq *PriceHistoryQuery) QueryProduct() *ProductQuery {
	query := (&ProductClient{config: phq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := phq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := phq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pricehistory.Table, pricehistory.FieldID, selector),
			sqlgraph.To(product.Table, product.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, pricehistory.ProductTable, pricehistory.ProductColumn),
		)
		fromU = sqlgraph.SetNeighbors(phq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PriceHistory entity from the query.
// Returns a *NotFoundError when no PriceHistory was found.
func (phq *PriceHistoryQuery) First(ctx context.Context) (*PriceHistory, error) {
	nodes, err := phq.Limit(1).All(setContextOp(ctx, phq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{pricehistory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (phq *PriceHistoryQuery) FirstX(ctx context.Context) *PriceHistory {
	node, err := phq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PriceHistory ID from the query.
// Returns a *NotFoundError when no PriceHistory ID was found.
func (phq *PriceHistoryQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = phq.Limit(1).IDs(setContextOp(ctx, phq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{pricehistory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (phq *PriceHistoryQuery) FirstIDX(ctx context.Context) int64 {
	id, err := phq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PriceHistory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PriceHistory entity is found.
// Returns a *NotFoundError when no PriceHistory entities are found.
func (phq *PriceHistoryQuery) Only(ctx context.Context) (*PriceHistory, error) {
	nodes, err := phq.Limit(2).All(setContextOp(ctx, phq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{pricehistory.Label}
	default:
		return nil, &NotSingularError{pricehistory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (phq *PriceHistoryQuery) OnlyX(ctx context.Context) *PriceHistory {
	node, err := phq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PriceHistory ID in the query.
// Returns a *NotSingularError when more than one PriceHistory ID is found.
// Returns a *NotFoundError when no entities are found.
func (phq *PriceHistoryQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = phq.Limit(2).IDs(setContextOp(ctx, phq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{pricehistory.Label}
	default:
		err = &NotSingularError{pricehistory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (phq *PriceHistoryQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := phq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PriceHistories.
func (phq *PriceHistoryQuery) All(ctx context.Context) ([]*PriceHistory, error) {
	ctx = setContextOp(ctx, phq.ctx, ent.OpQueryAll)
	if err := phq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PriceHistory, *PriceHistoryQuery]()
	return withInterceptors[[]*PriceHistory](ctx, phq, qr, phq.inters)
}

// AllX is like All, but panics if an error occurs.
func (phq *PriceHistoryQuery) AllX(ctx context.Context) []*PriceHistory {
	nodes, err := phq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PriceHistory IDs.
func (phq *PriceHistoryQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if phq.ctx.Unique == nil && phq.path != nil {
		phq.Unique(true)
	}
	ctx = setContextOp(ctx, phq.ctx, ent.OpQueryIDs)
	if err = phq.Select(pricehistory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (phq *PriceHistoryQuery) IDsX(ctx context.Context) []int64 {
	ids, err := phq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (phq *PriceHistoryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, phq.ctx, ent.OpQueryCount)
	if err := phq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, phq, querierCount[*PriceHistoryQuery](), phq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (phq *PriceHistoryQuery) CountX(ctx context.Context) int {
	count, err := phq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (phq *PriceHistoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, phq.ctx, ent.OpQueryExist)
	switch _, err := phq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (phq *PriceHistoryQuery) ExistX(ctx context.Context) bool {
	exist, err := phq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PriceHistoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (phq *PriceHistoryQuery) Clone() *PriceHistoryQuery {
	if phq == nil {
		return nil
	}
	return &PriceHistoryQuery{
		config:      phq.config,
		ctx:         phq.ctx.Clone(),
		order:       append([]pricehistory.OrderOption{}, phq.order...),
		inters:      append([]Interceptor{}, phq.inters...),
		predicates:  append([]predicate.PriceHistory{}, phq.predicates...),
		withProduct: phq.withProduct.Clone(),
		// clone intermediate query.
		sql:  phq.sql.Clone(),
		path: phq.path,
	}
}

// WithProduct tells the query-builder to eager-load the nodes that are connected to
// the "product" edge. The optional arguments are used to configure the query builder of the edge.
func (phq *PriceHistoryQuery) WithProduct(opts ...func(*ProductQuery)) *PriceHistoryQuery {
	query := (&ProductClient{config: phq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	phq.withProduct = query
	return phq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PriceHistory.Query().
//		GroupBy(pricehistory.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (phq *PriceHistoryQuery) GroupBy(field string, fields ...string) *PriceHistoryGroupBy {
	phq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PriceHistoryGroupBy{build: phq}
	grbuild.flds = &phq.ctx.Fields
	grbuild.label = pricehistory.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.PriceHistory.Query().
//		Select(pricehistory.FieldCreatedAt).
//		Scan(ctx, &v)
func (phq *PriceHistoryQuery) Select(fields ...string) *PriceHistorySelect {
	phq.ctx.Fields = append(phq.ctx.Fields, fields...)
	sbuild := &PriceHistorySelect{PriceHistoryQuery: phq}
	sbuild.label = pricehistory.Label
	sbuild.flds, sbuild.scan = &phq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PriceHistorySelect configured with the given aggregations.
func (phq *PriceHistoryQuery) Aggregate(fns ...AggregateFunc) *PriceHistorySelect {
	return phq.Select().Aggregate(fns...)
}

func (phq *PriceHistoryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range phq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, phq); err != nil {
				return err
			}
		}
	}
	for _, f := range phq.ctx.Fields {
		if !pricehistory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if phq.path != nil {
		prev, err := phq.path(ctx)
		if err != nil {
			return err
		}
		phq.sql = prev
	}
	return nil
}

func (phq *PriceHistoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PriceHistory, error) {
	var (
		nodes       = []*PriceHistory{}
		_spec       = phq.querySpec()
		loadedTypes = [1]bool{
			phq.withProduct != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PriceHistory).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PriceHistory{config: phq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(phq.modifiers) > 0 {
		_spec.Modifiers = phq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, phq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := phq.withProduct; query != nil {
		if err := phq.loadProduct(ctx, query, nodes, nil,
			func(n *PriceHistory, e *Product) { n.Edges.Product = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (phq *PriceHistoryQuery) loadProduct(ctx context.Context, query *ProductQuery, nodes []*PriceHistory, init func(*PriceHistory), assign func(*PriceHistory, *Product)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*PriceHistory)
	for i := range nodes {
		fk := nodes[i].ProductID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(product.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "product_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (phq *PriceHistoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := phq.querySpec()
	if len(phq.modifiers) > 0 {
		_spec.Modifiers = phq.modifiers
	}
	_spec.Node.Columns = phq.ctx.Fields
	if len(phq.ctx.Fields) > 0 {
		_spec.Unique = phq.ctx.Unique != nil && *phq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, phq.driver, _spec)
}

func (phq *PriceHistoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(pricehistory.Table, pricehistory.Columns, sqlgraph.NewFieldSpec(pricehistory.FieldID, field.TypeInt64))
	_spec.From = phq.sql
	if unique := phq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if phq.path != nil {
		_spec.Unique = true
	}
	if fields := phq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pricehistory.FieldID)
		for i := range fields {
			if fields[i] != pricehistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if phq.withProduct != nil {
			_spec.Node.AddColumnOnce(pricehistory.FieldProductID)
		}
	}
	if ps := phq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := phq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := phq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := phq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (phq *PriceHistoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(phq.driver.Dialect())
	t1 := builder.Table(pricehistory.Table)
	columns := phq.ctx.Fields
	if len(columns) == 0 {
		columns = pricehistory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if phq.sql != nil {
		selector = phq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if phq.ctx.Unique != nil && *phq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range phq.modifiers {
		m(selector)
	}
	for _, p := range phq.predicates {
		p(selector)
	}
	for _, p := range phq.order {
		p(selector)
	}
	if offset := phq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := phq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (phq *PriceHistoryQuery) Modify(modifiers ...func(s *sql.Selector)) *PriceHistorySelect {
	phq.modifiers = append(phq.modifiers, modifiers...)
	return phq.Select()
}

// PriceHistoryGroupBy is the group-by builder for PriceHistory entities.
type PriceHistoryGroupBy struct {
	selector
	build *PriceHistoryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (phgb *PriceHistoryGroupBy) Aggregate(fns ...AggregateFunc) *PriceHistoryGroupBy {
	phgb.fns = append(phgb.fns, fns...)
	return phgb
}

// Scan applies the selector query and scans the result into the given value.
func (phgb *PriceHistoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, phgb.build.ctx, ent.OpQueryGroupBy)
	if err := phgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PriceHistoryQuery, *PriceHistoryGroupBy](ctx, phgb.build, phgb, phgb.build.inters, v)
}

func (phgb *PriceHistoryGroupBy) sqlScan(ctx context.Context, root *PriceHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(phgb.fns))
	for _, fn := range phgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*phgb.flds)+len(phgb.fns))
		for _, f := range *phgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*phgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := phgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PriceHistorySelect is the builder for selecting fields of PriceHistory entities.
type PriceHistorySelect struct {
	*PriceHistoryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (phs *PriceHistorySelect) Aggregate(fns ...AggregateFunc) *PriceHistorySelect {
	phs.fns = append(phs.fns, fns...)
	return phs
}

// Scan applies the selector query and scans the result into the given value.
func (phs *PriceHistorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, phs.ctx, ent.OpQuerySelect)
	if err := phs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PriceHistoryQuery, *PriceHistorySelect](ctx, phs.PriceHistoryQuery, phs, phs.inters, v)
}

func (phs *PriceHistorySelect) sqlScan(ctx context.Context, root *PriceHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(phs.fns))
	for _, fn := range phs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*phs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := phs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (phs *PriceHistorySelect) Modify(modifiers ...func(s *sql.Selector)) *PriceHistorySelect {
	phs.modifiers = append(phs.modifiers, modifiers...)
	return phs
}
