// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shopspring/decimal"
	"gitlab.calendaria.team/services/products/ent/enum"
	"gitlab.calendaria.team/services/products/ent/pricehistory"
	"gitlab.calendaria.team/services/products/ent/product"
)

// PriceHistoryCreate is the builder for creating a PriceHistory entity.
type PriceHistoryCreate struct {
	config
	mutation *PriceHistoryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (phc *PriceHistoryCreate) SetCreatedAt(t time.Time) *PriceHistoryCreate {
	phc.mutation.SetCreatedAt(t)
	return phc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (phc *PriceHistoryCreate) SetNillableCreatedAt(t *time.Time) *PriceHistoryCreate {
	if t != nil {
		phc.SetCreatedAt(*t)
	}
	return phc
}

// SetUpdatedAt sets the "updated_at" field.
func (phc *PriceHistoryCreate) SetUpdatedAt(t time.Time) *PriceHistoryCreate {
	phc.mutation.SetUpdatedAt(t)
	return phc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (phc *PriceHistoryCreate) SetNillableUpdatedAt(t *time.Time) *PriceHistoryCreate {
	if t != nil {
		phc.SetUpdatedAt(*t)
	}
	return phc
}

// SetTenantID sets the "tenant_id" field.
func (phc *PriceHistoryCreate) SetTenantID(i int64) *PriceHistoryCreate {
	phc.mutation.SetTenantID(i)
	return phc
}

// SetProductID sets the "product_id" field.
func (phc *PriceHistoryCreate) SetProductID(i int64) *PriceHistoryCreate {
	phc.mutation.SetProductID(i)
	return phc
}

// SetPriceType sets the "price_type" field.
func (phc *PriceHistoryCreate) SetPriceType(et enum.PriceType) *PriceHistoryCreate {
	phc.mutation.SetPriceType(et)
	return phc
}

// SetOldPrice sets the "old_price" field.
func (phc *PriceHistoryCreate) SetOldPrice(d decimal.Decimal) *PriceHistoryCreate {
	phc.mutation.SetOldPrice(d)
	return phc
}

// SetNewPrice sets the "new_price" field.
func (phc *PriceHistoryCreate) SetNewPrice(d decimal.Decimal) *PriceHistoryCreate {
	phc.mutation.SetNewPrice(d)
	return phc
}

// SetChangedBy sets the "changed_by" field.
func (phc *PriceHistoryCreate) SetChangedBy(i int64) *PriceHistoryCreate {
	phc.mutation.SetChangedBy(i)
	return phc
}

// SetReason sets the "reason" field.
func (phc *PriceHistoryCreate) SetReason(s string) *PriceHistoryCreate {
	phc.mutation.SetReason(s)
	return phc
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (phc *PriceHistoryCreate) SetNillableReason(s *string) *PriceHistoryCreate {
	if s != nil {
		phc.SetReason(*s)
	}
	return phc
}

// SetChangedAt sets the "changed_at" field.
func (phc *PriceHistoryCreate) SetChangedAt(t time.Time) *PriceHistoryCreate {
	phc.mutation.SetChangedAt(t)
	return phc
}

// SetNillableChangedAt sets the "changed_at" field if the given value is not nil.
func (phc *PriceHistoryCreate) SetNillableChangedAt(t *time.Time) *PriceHistoryCreate {
	if t != nil {
		phc.SetChangedAt(*t)
	}
	return phc
}

// SetID sets the "id" field.
func (phc *PriceHistoryCreate) SetID(i int64) *PriceHistoryCreate {
	phc.mutation.SetID(i)
	return phc
}

// SetProduct sets the "product" edge to the Product entity.
func (phc *PriceHistoryCreate) SetProduct(p *Product) *PriceHistoryCreate {
	return phc.SetProductID(p.ID)
}

// Mutation returns the PriceHistoryMutation object of the builder.
func (phc *PriceHistoryCreate) Mutation() *PriceHistoryMutation {
	return phc.mutation
}

// Save creates the PriceHistory in the database.
func (phc *PriceHistoryCreate) Save(ctx context.Context) (*PriceHistory, error) {
	phc.defaults()
	return withHooks(ctx, phc.sqlSave, phc.mutation, phc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (phc *PriceHistoryCreate) SaveX(ctx context.Context) *PriceHistory {
	v, err := phc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (phc *PriceHistoryCreate) Exec(ctx context.Context) error {
	_, err := phc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (phc *PriceHistoryCreate) ExecX(ctx context.Context) {
	if err := phc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (phc *PriceHistoryCreate) defaults() {
	if _, ok := phc.mutation.CreatedAt(); !ok {
		v := pricehistory.DefaultCreatedAt()
		phc.mutation.SetCreatedAt(v)
	}
	if _, ok := phc.mutation.UpdatedAt(); !ok {
		v := pricehistory.DefaultUpdatedAt()
		phc.mutation.SetUpdatedAt(v)
	}
	if _, ok := phc.mutation.Reason(); !ok {
		v := pricehistory.DefaultReason
		phc.mutation.SetReason(v)
	}
	if _, ok := phc.mutation.ChangedAt(); !ok {
		v := pricehistory.DefaultChangedAt()
		phc.mutation.SetChangedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (phc *PriceHistoryCreate) check() error {
	if _, ok := phc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PriceHistory.created_at"`)}
	}
	if _, ok := phc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PriceHistory.updated_at"`)}
	}
	if _, ok := phc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "PriceHistory.tenant_id"`)}
	}
	if _, ok := phc.mutation.ProductID(); !ok {
		return &ValidationError{Name: "product_id", err: errors.New(`ent: missing required field "PriceHistory.product_id"`)}
	}
	if _, ok := phc.mutation.PriceType(); !ok {
		return &ValidationError{Name: "price_type", err: errors.New(`ent: missing required field "PriceHistory.price_type"`)}
	}
	if v, ok := phc.mutation.PriceType(); ok {
		if err := pricehistory.PriceTypeValidator(v); err != nil {
			return &ValidationError{Name: "price_type", err: fmt.Errorf(`ent: validator failed for field "PriceHistory.price_type": %w`, err)}
		}
	}
	if _, ok := phc.mutation.OldPrice(); !ok {
		return &ValidationError{Name: "old_price", err: errors.New(`ent: missing required field "PriceHistory.old_price"`)}
	}
	if _, ok := phc.mutation.NewPrice(); !ok {
		return &ValidationError{Name: "new_price", err: errors.New(`ent: missing required field "PriceHistory.new_price"`)}
	}
	if _, ok := phc.mutation.ChangedBy(); !ok {
		return &ValidationError{Name: "changed_by", err: errors.New(`ent: missing required field "PriceHistory.changed_by"`)}
	}
	if _, ok := phc.mutation.ChangedAt(); !ok {
		return &ValidationError{Name: "changed_at", err: errors.New(`ent: missing required field "PriceHistory.changed_at"`)}
	}
	if len(phc.mutation.ProductIDs()) == 0 {
		return &ValidationError{Name: "product", err: errors.New(`ent: missing required edge "PriceHistory.product"`)}
	}
	return nil
}

func (phc *PriceHistoryCreate) sqlSave(ctx context.Context) (*PriceHistory, error) {
	if err := phc.check(); err != nil {
		return nil, err
	}
	_node, _spec := phc.createSpec()
	if err := sqlgraph.CreateNode(ctx, phc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	phc.mutation.id = &_node.ID
	phc.mutation.done = true
	return _node, nil
}

func (phc *PriceHistoryCreate) createSpec() (*PriceHistory, *sqlgraph.CreateSpec) {
	var (
		_node = &PriceHistory{config: phc.config}
		_spec = sqlgraph.NewCreateSpec(pricehistory.Table, sqlgraph.NewFieldSpec(pricehistory.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = phc.conflict
	if id, ok := phc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := phc.mutation.CreatedAt(); ok {
		_spec.SetField(pricehistory.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := phc.mutation.UpdatedAt(); ok {
		_spec.SetField(pricehistory.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := phc.mutation.TenantID(); ok {
		_spec.SetField(pricehistory.FieldTenantID, field.TypeInt64, value)
		_node.TenantID = value
	}
	if value, ok := phc.mutation.PriceType(); ok {
		_spec.SetField(pricehistory.FieldPriceType, field.TypeEnum, value)
		_node.PriceType = value
	}
	if value, ok := phc.mutation.OldPrice(); ok {
		_spec.SetField(pricehistory.FieldOldPrice, field.TypeFloat64, value)
		_node.OldPrice = value
	}
	if value, ok := phc.mutation.NewPrice(); ok {
		_spec.SetField(pricehistory.FieldNewPrice, field.TypeFloat64, value)
		_node.NewPrice = value
	}
	if value, ok := phc.mutation.ChangedBy(); ok {
		_spec.SetField(pricehistory.FieldChangedBy, field.TypeInt64, value)
		_node.ChangedBy = value
	}
	if value, ok := phc.mutation.Reason(); ok {
		_spec.SetField(pricehistory.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := phc.mutation.ChangedAt(); ok {
		_spec.SetField(pricehistory.FieldChangedAt, field.TypeTime, value)
		_node.ChangedAt = value
	}
	if nodes := phc.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   pricehistory.ProductTable,
			Columns: []string{pricehistory.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProductID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PriceHistory.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PriceHistoryUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (phc *PriceHistoryCreate) OnConflict(opts ...sql.ConflictOption) *PriceHistoryUpsertOne {
	phc.conflict = opts
	return &PriceHistoryUpsertOne{
		create: phc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PriceHistory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (phc *PriceHistoryCreate) OnConflictColumns(columns ...string) *PriceHistoryUpsertOne {
	phc.conflict = append(phc.conflict, sql.ConflictColumns(columns...))
	return &PriceHistoryUpsertOne{
		create: phc,
	}
}

type (
	// PriceHistoryUpsertOne is the builder for "upsert"-ing
	//  one PriceHistory node.
	PriceHistoryUpsertOne struct {
		create *PriceHistoryCreate
	}

	// PriceHistoryUpsert is the "OnConflict" setter.
	PriceHistoryUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PriceHistoryUpsert) SetUpdatedAt(v time.Time) *PriceHistoryUpsert {
	u.Set(pricehistory.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PriceHistoryUpsert) UpdateUpdatedAt() *PriceHistoryUpsert {
	u.SetExcluded(pricehistory.FieldUpdatedAt)
	return u
}

// SetProductID sets the "product_id" field.
func (u *PriceHistoryUpsert) SetProductID(v int64) *PriceHistoryUpsert {
	u.Set(pricehistory.FieldProductID, v)
	return u
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *PriceHistoryUpsert) UpdateProductID() *PriceHistoryUpsert {
	u.SetExcluded(pricehistory.FieldProductID)
	return u
}

// SetReason sets the "reason" field.
func (u *PriceHistoryUpsert) SetReason(v string) *PriceHistoryUpsert {
	u.Set(pricehistory.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *PriceHistoryUpsert) UpdateReason() *PriceHistoryUpsert {
	u.SetExcluded(pricehistory.FieldReason)
	return u
}

// ClearReason clears the value of the "reason" field.
func (u *PriceHistoryUpsert) ClearReason() *PriceHistoryUpsert {
	u.SetNull(pricehistory.FieldReason)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.PriceHistory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(pricehistory.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PriceHistoryUpsertOne) UpdateNewValues() *PriceHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(pricehistory.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(pricehistory.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(pricehistory.FieldTenantID)
		}
		if _, exists := u.create.mutation.PriceType(); exists {
			s.SetIgnore(pricehistory.FieldPriceType)
		}
		if _, exists := u.create.mutation.OldPrice(); exists {
			s.SetIgnore(pricehistory.FieldOldPrice)
		}
		if _, exists := u.create.mutation.NewPrice(); exists {
			s.SetIgnore(pricehistory.FieldNewPrice)
		}
		if _, exists := u.create.mutation.ChangedBy(); exists {
			s.SetIgnore(pricehistory.FieldChangedBy)
		}
		if _, exists := u.create.mutation.ChangedAt(); exists {
			s.SetIgnore(pricehistory.FieldChangedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PriceHistory.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PriceHistoryUpsertOne) Ignore() *PriceHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PriceHistoryUpsertOne) DoNothing() *PriceHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PriceHistoryCreate.OnConflict
// documentation for more info.
func (u *PriceHistoryUpsertOne) Update(set func(*PriceHistoryUpsert)) *PriceHistoryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PriceHistoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PriceHistoryUpsertOne) SetUpdatedAt(v time.Time) *PriceHistoryUpsertOne {
	return u.Update(func(s *PriceHistoryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PriceHistoryUpsertOne) UpdateUpdatedAt() *PriceHistoryUpsertOne {
	return u.Update(func(s *PriceHistoryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetProductID sets the "product_id" field.
func (u *PriceHistoryUpsertOne) SetProductID(v int64) *PriceHistoryUpsertOne {
	return u.Update(func(s *PriceHistoryUpsert) {
		s.SetProductID(v)
	})
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *PriceHistoryUpsertOne) UpdateProductID() *PriceHistoryUpsertOne {
	return u.Update(func(s *PriceHistoryUpsert) {
		s.UpdateProductID()
	})
}

// SetReason sets the "reason" field.
func (u *PriceHistoryUpsertOne) SetReason(v string) *PriceHistoryUpsertOne {
	return u.Update(func(s *PriceHistoryUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *PriceHistoryUpsertOne) UpdateReason() *PriceHistoryUpsertOne {
	return u.Update(func(s *PriceHistoryUpsert) {
		s.UpdateReason()
	})
}

// ClearReason clears the value of the "reason" field.
func (u *PriceHistoryUpsertOne) ClearReason() *PriceHistoryUpsertOne {
	return u.Update(func(s *PriceHistoryUpsert) {
		s.ClearReason()
	})
}

// Exec executes the query.
func (u *PriceHistoryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PriceHistoryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PriceHistoryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PriceHistoryUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PriceHistoryUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PriceHistoryCreateBulk is the builder for creating many PriceHistory entities in bulk.
type PriceHistoryCreateBulk struct {
	config
	err      error
	builders []*PriceHistoryCreate
	conflict []sql.ConflictOption
}

// Save creates the PriceHistory entities in the database.
func (phcb *PriceHistoryCreateBulk) Save(ctx context.Context) ([]*PriceHistory, error) {
	if phcb.err != nil {
		return nil, phcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(phcb.builders))
	nodes := make([]*PriceHistory, len(phcb.builders))
	mutators := make([]Mutator, len(phcb.builders))
	for i := range phcb.builders {
		func(i int, root context.Context) {
			builder := phcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PriceHistoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, phcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = phcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, phcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, phcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (phcb *PriceHistoryCreateBulk) SaveX(ctx context.Context) []*PriceHistory {
	v, err := phcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (phcb *PriceHistoryCreateBulk) Exec(ctx context.Context) error {
	_, err := phcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (phcb *PriceHistoryCreateBulk) ExecX(ctx context.Context) {
	if err := phcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PriceHistory.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PriceHistoryUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (phcb *PriceHistoryCreateBulk) OnConflict(opts ...sql.ConflictOption) *PriceHistoryUpsertBulk {
	phcb.conflict = opts
	return &PriceHistoryUpsertBulk{
		create: phcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PriceHistory.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (phcb *PriceHistoryCreateBulk) OnConflictColumns(columns ...string) *PriceHistoryUpsertBulk {
	phcb.conflict = append(phcb.conflict, sql.ConflictColumns(columns...))
	return &PriceHistoryUpsertBulk{
		create: phcb,
	}
}

// PriceHistoryUpsertBulk is the builder for "upsert"-ing
// a bulk of PriceHistory nodes.
type PriceHistoryUpsertBulk struct {
	create *PriceHistoryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PriceHistory.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(pricehistory.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PriceHistoryUpsertBulk) UpdateNewValues() *PriceHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(pricehistory.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(pricehistory.FieldCreatedAt)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(pricehistory.FieldTenantID)
			}
			if _, exists := b.mutation.PriceType(); exists {
				s.SetIgnore(pricehistory.FieldPriceType)
			}
			if _, exists := b.mutation.OldPrice(); exists {
				s.SetIgnore(pricehistory.FieldOldPrice)
			}
			if _, exists := b.mutation.NewPrice(); exists {
				s.SetIgnore(pricehistory.FieldNewPrice)
			}
			if _, exists := b.mutation.ChangedBy(); exists {
				s.SetIgnore(pricehistory.FieldChangedBy)
			}
			if _, exists := b.mutation.ChangedAt(); exists {
				s.SetIgnore(pricehistory.FieldChangedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PriceHistory.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PriceHistoryUpsertBulk) Ignore() *PriceHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PriceHistoryUpsertBulk) DoNothing() *PriceHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PriceHistoryCreateBulk.OnConflict
// documentation for more info.
func (u *PriceHistoryUpsertBulk) Update(set func(*PriceHistoryUpsert)) *PriceHistoryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PriceHistoryUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PriceHistoryUpsertBulk) SetUpdatedAt(v time.Time) *PriceHistoryUpsertBulk {
	return u.Update(func(s *PriceHistoryUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PriceHistoryUpsertBulk) UpdateUpdatedAt() *PriceHistoryUpsertBulk {
	return u.Update(func(s *PriceHistoryUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetProductID sets the "product_id" field.
func (u *PriceHistoryUpsertBulk) SetProductID(v int64) *PriceHistoryUpsertBulk {
	return u.Update(func(s *PriceHistoryUpsert) {
		s.SetProductID(v)
	})
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *PriceHistoryUpsertBulk) UpdateProductID() *PriceHistoryUpsertBulk {
	return u.Update(func(s *PriceHistoryUpsert) {
		s.UpdateProductID()
	})
}

// SetReason sets the "reason" field.
func (u *PriceHistoryUpsertBulk) SetReason(v string) *PriceHistoryUpsertBulk {
	return u.Update(func(s *PriceHistoryUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *PriceHistoryUpsertBulk) UpdateReason() *PriceHistoryUpsertBulk {
	return u.Update(func(s *PriceHistoryUpsert) {
		s.UpdateReason()
	})
}

// ClearReason clears the value of the "reason" field.
func (u *PriceHistoryUpsertBulk) ClearReason() *PriceHistoryUpsertBulk {
	return u.Update(func(s *PriceHistoryUpsert) {
		s.ClearReason()
	})
}

// Exec executes the query.
func (u *PriceHistoryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PriceHistoryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PriceHistoryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PriceHistoryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
