// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/shopspring/decimal"
	"github.com/makesalekz/products/ent/barcode"
	"github.com/makesalekz/products/ent/enum"
	"github.com/makesalekz/products/ent/predicate"
	"github.com/makesalekz/products/ent/pricehistory"
	"github.com/makesalekz/products/ent/product"
)

// ProductUpdate is the builder for updating Product entities.
type ProductUpdate struct {
	config
	hooks     []Hook
	mutation  *ProductMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ProductUpdate builder.
func (pu *ProductUpdate) Where(ps ...predicate.Product) *ProductUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetUpdatedAt sets the "updated_at" field.
func (pu *ProductUpdate) SetUpdatedAt(t time.Time) *ProductUpdate {
	pu.mutation.SetUpdatedAt(t)
	return pu
}

// SetDeletedAt sets the "deleted_at" field.
func (pu *ProductUpdate) SetDeletedAt(t time.Time) *ProductUpdate {
	pu.mutation.SetDeletedAt(t)
	return pu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableDeletedAt(t *time.Time) *ProductUpdate {
	if t != nil {
		pu.SetDeletedAt(*t)
	}
	return pu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (pu *ProductUpdate) ClearDeletedAt() *ProductUpdate {
	pu.mutation.ClearDeletedAt()
	return pu
}

// SetName sets the "name" field.
func (pu *ProductUpdate) SetName(s string) *ProductUpdate {
	pu.mutation.SetName(s)
	return pu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableName(s *string) *ProductUpdate {
	if s != nil {
		pu.SetName(*s)
	}
	return pu
}

// SetBarcode sets the "barcode" field.
func (pu *ProductUpdate) SetBarcode(s string) *ProductUpdate {
	pu.mutation.SetBarcode(s)
	return pu
}

// SetNillableBarcode sets the "barcode" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableBarcode(s *string) *ProductUpdate {
	if s != nil {
		pu.SetBarcode(*s)
	}
	return pu
}

// ClearBarcode clears the value of the "barcode" field.
func (pu *ProductUpdate) ClearBarcode() *ProductUpdate {
	pu.mutation.ClearBarcode()
	return pu
}

// SetCategoryID sets the "category_id" field.
func (pu *ProductUpdate) SetCategoryID(i int64) *ProductUpdate {
	pu.mutation.ResetCategoryID()
	pu.mutation.SetCategoryID(i)
	return pu
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableCategoryID(i *int64) *ProductUpdate {
	if i != nil {
		pu.SetCategoryID(*i)
	}
	return pu
}

// AddCategoryID adds i to the "category_id" field.
func (pu *ProductUpdate) AddCategoryID(i int64) *ProductUpdate {
	pu.mutation.AddCategoryID(i)
	return pu
}

// ClearCategoryID clears the value of the "category_id" field.
func (pu *ProductUpdate) ClearCategoryID() *ProductUpdate {
	pu.mutation.ClearCategoryID()
	return pu
}

// SetUnit sets the "unit" field.
func (pu *ProductUpdate) SetUnit(et enum.UnitType) *ProductUpdate {
	pu.mutation.SetUnit(et)
	return pu
}

// SetNillableUnit sets the "unit" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableUnit(et *enum.UnitType) *ProductUpdate {
	if et != nil {
		pu.SetUnit(*et)
	}
	return pu
}

// SetPurchasePrice sets the "purchase_price" field.
func (pu *ProductUpdate) SetPurchasePrice(d decimal.Decimal) *ProductUpdate {
	pu.mutation.ResetPurchasePrice()
	pu.mutation.SetPurchasePrice(d)
	return pu
}

// SetNillablePurchasePrice sets the "purchase_price" field if the given value is not nil.
func (pu *ProductUpdate) SetNillablePurchasePrice(d *decimal.Decimal) *ProductUpdate {
	if d != nil {
		pu.SetPurchasePrice(*d)
	}
	return pu
}

// AddPurchasePrice adds d to the "purchase_price" field.
func (pu *ProductUpdate) AddPurchasePrice(d decimal.Decimal) *ProductUpdate {
	pu.mutation.AddPurchasePrice(d)
	return pu
}

// ClearPurchasePrice clears the value of the "purchase_price" field.
func (pu *ProductUpdate) ClearPurchasePrice() *ProductUpdate {
	pu.mutation.ClearPurchasePrice()
	return pu
}

// SetSellingPrice sets the "selling_price" field.
func (pu *ProductUpdate) SetSellingPrice(d decimal.Decimal) *ProductUpdate {
	pu.mutation.ResetSellingPrice()
	pu.mutation.SetSellingPrice(d)
	return pu
}

// SetNillableSellingPrice sets the "selling_price" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableSellingPrice(d *decimal.Decimal) *ProductUpdate {
	if d != nil {
		pu.SetSellingPrice(*d)
	}
	return pu
}

// AddSellingPrice adds d to the "selling_price" field.
func (pu *ProductUpdate) AddSellingPrice(d decimal.Decimal) *ProductUpdate {
	pu.mutation.AddSellingPrice(d)
	return pu
}

// ClearSellingPrice clears the value of the "selling_price" field.
func (pu *ProductUpdate) ClearSellingPrice() *ProductUpdate {
	pu.mutation.ClearSellingPrice()
	return pu
}

// SetDescription sets the "description" field.
func (pu *ProductUpdate) SetDescription(s string) *ProductUpdate {
	pu.mutation.SetDescription(s)
	return pu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableDescription(s *string) *ProductUpdate {
	if s != nil {
		pu.SetDescription(*s)
	}
	return pu
}

// ClearDescription clears the value of the "description" field.
func (pu *ProductUpdate) ClearDescription() *ProductUpdate {
	pu.mutation.ClearDescription()
	return pu
}

// SetSku sets the "sku" field.
func (pu *ProductUpdate) SetSku(s string) *ProductUpdate {
	pu.mutation.SetSku(s)
	return pu
}

// SetNillableSku sets the "sku" field if the given value is not nil.
func (pu *ProductUpdate) SetNillableSku(s *string) *ProductUpdate {
	if s != nil {
		pu.SetSku(*s)
	}
	return pu
}

// ClearSku clears the value of the "sku" field.
func (pu *ProductUpdate) ClearSku() *ProductUpdate {
	pu.mutation.ClearSku()
	return pu
}

// AddBarcodeIDs adds the "barcodes" edge to the Barcode entity by IDs.
func (pu *ProductUpdate) AddBarcodeIDs(ids ...int64) *ProductUpdate {
	pu.mutation.AddBarcodeIDs(ids...)
	return pu
}

// AddBarcodes adds the "barcodes" edges to the Barcode entity.
func (pu *ProductUpdate) AddBarcodes(b ...*Barcode) *ProductUpdate {
	ids := make([]int64, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return pu.AddBarcodeIDs(ids...)
}

// AddPriceHistoryIDs adds the "price_histories" edge to the PriceHistory entity by IDs.
func (pu *ProductUpdate) AddPriceHistoryIDs(ids ...int64) *ProductUpdate {
	pu.mutation.AddPriceHistoryIDs(ids...)
	return pu
}

// AddPriceHistories adds the "price_histories" edges to the PriceHistory entity.
func (pu *ProductUpdate) AddPriceHistories(p ...*PriceHistory) *ProductUpdate {
	ids := make([]int64, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pu.AddPriceHistoryIDs(ids...)
}

// Mutation returns the ProductMutation object of the builder.
func (pu *ProductUpdate) Mutation() *ProductMutation {
	return pu.mutation
}

// ClearBarcodes clears all "barcodes" edges to the Barcode entity.
func (pu *ProductUpdate) ClearBarcodes() *ProductUpdate {
	pu.mutation.ClearBarcodes()
	return pu
}

// RemoveBarcodeIDs removes the "barcodes" edge to Barcode entities by IDs.
func (pu *ProductUpdate) RemoveBarcodeIDs(ids ...int64) *ProductUpdate {
	pu.mutation.RemoveBarcodeIDs(ids...)
	return pu
}

// RemoveBarcodes removes "barcodes" edges to Barcode entities.
func (pu *ProductUpdate) RemoveBarcodes(b ...*Barcode) *ProductUpdate {
	ids := make([]int64, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return pu.RemoveBarcodeIDs(ids...)
}

// ClearPriceHistories clears all "price_histories" edges to the PriceHistory entity.
func (pu *ProductUpdate) ClearPriceHistories() *ProductUpdate {
	pu.mutation.ClearPriceHistories()
	return pu
}

// RemovePriceHistoryIDs removes the "price_histories" edge to PriceHistory entities by IDs.
func (pu *ProductUpdate) RemovePriceHistoryIDs(ids ...int64) *ProductUpdate {
	pu.mutation.RemovePriceHistoryIDs(ids...)
	return pu
}

// RemovePriceHistories removes "price_histories" edges to PriceHistory entities.
func (pu *ProductUpdate) RemovePriceHistories(p ...*PriceHistory) *ProductUpdate {
	ids := make([]int64, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pu.RemovePriceHistoryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *ProductUpdate) Save(ctx context.Context) (int, error) {
	if err := pu.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *ProductUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *ProductUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *ProductUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pu *ProductUpdate) defaults() error {
	if _, ok := pu.mutation.UpdatedAt(); !ok {
		if product.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized product.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := product.UpdateDefaultUpdatedAt()
		pu.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (pu *ProductUpdate) check() error {
	if v, ok := pu.mutation.Name(); ok {
		if err := product.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Product.name": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Unit(); ok {
		if err := product.UnitValidator(v); err != nil {
			return &ValidationError{Name: "unit", err: fmt.Errorf(`ent: validator failed for field "Product.unit": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (pu *ProductUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ProductUpdate {
	pu.modifiers = append(pu.modifiers, modifiers...)
	return pu
}

func (pu *ProductUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(product.Table, product.Columns, sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt64))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.UpdatedAt(); ok {
		_spec.SetField(product.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := pu.mutation.DeletedAt(); ok {
		_spec.SetField(product.FieldDeletedAt, field.TypeTime, value)
	}
	if pu.mutation.DeletedAtCleared() {
		_spec.ClearField(product.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := pu.mutation.Name(); ok {
		_spec.SetField(product.FieldName, field.TypeString, value)
	}
	if value, ok := pu.mutation.Barcode(); ok {
		_spec.SetField(product.FieldBarcode, field.TypeString, value)
	}
	if pu.mutation.BarcodeCleared() {
		_spec.ClearField(product.FieldBarcode, field.TypeString)
	}
	if value, ok := pu.mutation.CategoryID(); ok {
		_spec.SetField(product.FieldCategoryID, field.TypeInt64, value)
	}
	if value, ok := pu.mutation.AddedCategoryID(); ok {
		_spec.AddField(product.FieldCategoryID, field.TypeInt64, value)
	}
	if pu.mutation.CategoryIDCleared() {
		_spec.ClearField(product.FieldCategoryID, field.TypeInt64)
	}
	if value, ok := pu.mutation.Unit(); ok {
		_spec.SetField(product.FieldUnit, field.TypeEnum, value)
	}
	if value, ok := pu.mutation.PurchasePrice(); ok {
		_spec.SetField(product.FieldPurchasePrice, field.TypeFloat64, value)
	}
	if value, ok := pu.mutation.AddedPurchasePrice(); ok {
		_spec.AddField(product.FieldPurchasePrice, field.TypeFloat64, value)
	}
	if pu.mutation.PurchasePriceCleared() {
		_spec.ClearField(product.FieldPurchasePrice, field.TypeFloat64)
	}
	if value, ok := pu.mutation.SellingPrice(); ok {
		_spec.SetField(product.FieldSellingPrice, field.TypeFloat64, value)
	}
	if value, ok := pu.mutation.AddedSellingPrice(); ok {
		_spec.AddField(product.FieldSellingPrice, field.TypeFloat64, value)
	}
	if pu.mutation.SellingPriceCleared() {
		_spec.ClearField(product.FieldSellingPrice, field.TypeFloat64)
	}
	if value, ok := pu.mutation.Description(); ok {
		_spec.SetField(product.FieldDescription, field.TypeString, value)
	}
	if pu.mutation.DescriptionCleared() {
		_spec.ClearField(product.FieldDescription, field.TypeString)
	}
	if value, ok := pu.mutation.Sku(); ok {
		_spec.SetField(product.FieldSku, field.TypeString, value)
	}
	if pu.mutation.SkuCleared() {
		_spec.ClearField(product.FieldSku, field.TypeString)
	}
	if pu.mutation.BarcodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   product.BarcodesTable,
			Columns: []string{product.BarcodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(barcode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.RemovedBarcodesIDs(); len(nodes) > 0 && !pu.mutation.BarcodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   product.BarcodesTable,
			Columns: []string{product.BarcodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(barcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.BarcodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   product.BarcodesTable,
			Columns: []string{product.BarcodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(barcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if pu.mutation.PriceHistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   product.PriceHistoriesTable,
			Columns: []string{product.PriceHistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricehistory.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.RemovedPriceHistoriesIDs(); len(nodes) > 0 && !pu.mutation.PriceHistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   product.PriceHistoriesTable,
			Columns: []string{product.PriceHistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricehistory.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.PriceHistoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   product.PriceHistoriesTable,
			Columns: []string{product.PriceHistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricehistory.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(pu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{product.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// ProductUpdateOne is the builder for updating a single Product entity.
type ProductUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ProductMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (puo *ProductUpdateOne) SetUpdatedAt(t time.Time) *ProductUpdateOne {
	puo.mutation.SetUpdatedAt(t)
	return puo
}

// SetDeletedAt sets the "deleted_at" field.
func (puo *ProductUpdateOne) SetDeletedAt(t time.Time) *ProductUpdateOne {
	puo.mutation.SetDeletedAt(t)
	return puo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableDeletedAt(t *time.Time) *ProductUpdateOne {
	if t != nil {
		puo.SetDeletedAt(*t)
	}
	return puo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (puo *ProductUpdateOne) ClearDeletedAt() *ProductUpdateOne {
	puo.mutation.ClearDeletedAt()
	return puo
}

// SetName sets the "name" field.
func (puo *ProductUpdateOne) SetName(s string) *ProductUpdateOne {
	puo.mutation.SetName(s)
	return puo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableName(s *string) *ProductUpdateOne {
	if s != nil {
		puo.SetName(*s)
	}
	return puo
}

// SetBarcode sets the "barcode" field.
func (puo *ProductUpdateOne) SetBarcode(s string) *ProductUpdateOne {
	puo.mutation.SetBarcode(s)
	return puo
}

// SetNillableBarcode sets the "barcode" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableBarcode(s *string) *ProductUpdateOne {
	if s != nil {
		puo.SetBarcode(*s)
	}
	return puo
}

// ClearBarcode clears the value of the "barcode" field.
func (puo *ProductUpdateOne) ClearBarcode() *ProductUpdateOne {
	puo.mutation.ClearBarcode()
	return puo
}

// SetCategoryID sets the "category_id" field.
func (puo *ProductUpdateOne) SetCategoryID(i int64) *ProductUpdateOne {
	puo.mutation.ResetCategoryID()
	puo.mutation.SetCategoryID(i)
	return puo
}

// SetNillableCategoryID sets the "category_id" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableCategoryID(i *int64) *ProductUpdateOne {
	if i != nil {
		puo.SetCategoryID(*i)
	}
	return puo
}

// AddCategoryID adds i to the "category_id" field.
func (puo *ProductUpdateOne) AddCategoryID(i int64) *ProductUpdateOne {
	puo.mutation.AddCategoryID(i)
	return puo
}

// ClearCategoryID clears the value of the "category_id" field.
func (puo *ProductUpdateOne) ClearCategoryID() *ProductUpdateOne {
	puo.mutation.ClearCategoryID()
	return puo
}

// SetUnit sets the "unit" field.
func (puo *ProductUpdateOne) SetUnit(et enum.UnitType) *ProductUpdateOne {
	puo.mutation.SetUnit(et)
	return puo
}

// SetNillableUnit sets the "unit" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableUnit(et *enum.UnitType) *ProductUpdateOne {
	if et != nil {
		puo.SetUnit(*et)
	}
	return puo
}

// SetPurchasePrice sets the "purchase_price" field.
func (puo *ProductUpdateOne) SetPurchasePrice(d decimal.Decimal) *ProductUpdateOne {
	puo.mutation.ResetPurchasePrice()
	puo.mutation.SetPurchasePrice(d)
	return puo
}

// SetNillablePurchasePrice sets the "purchase_price" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillablePurchasePrice(d *decimal.Decimal) *ProductUpdateOne {
	if d != nil {
		puo.SetPurchasePrice(*d)
	}
	return puo
}

// AddPurchasePrice adds d to the "purchase_price" field.
func (puo *ProductUpdateOne) AddPurchasePrice(d decimal.Decimal) *ProductUpdateOne {
	puo.mutation.AddPurchasePrice(d)
	return puo
}

// ClearPurchasePrice clears the value of the "purchase_price" field.
func (puo *ProductUpdateOne) ClearPurchasePrice() *ProductUpdateOne {
	puo.mutation.ClearPurchasePrice()
	return puo
}

// SetSellingPrice sets the "selling_price" field.
func (puo *ProductUpdateOne) SetSellingPrice(d decimal.Decimal) *ProductUpdateOne {
	puo.mutation.ResetSellingPrice()
	puo.mutation.SetSellingPrice(d)
	return puo
}

// SetNillableSellingPrice sets the "selling_price" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableSellingPrice(d *decimal.Decimal) *ProductUpdateOne {
	if d != nil {
		puo.SetSellingPrice(*d)
	}
	return puo
}

// AddSellingPrice adds d to the "selling_price" field.
func (puo *ProductUpdateOne) AddSellingPrice(d decimal.Decimal) *ProductUpdateOne {
	puo.mutation.AddSellingPrice(d)
	return puo
}

// ClearSellingPrice clears the value of the "selling_price" field.
func (puo *ProductUpdateOne) ClearSellingPrice() *ProductUpdateOne {
	puo.mutation.ClearSellingPrice()
	return puo
}

// SetDescription sets the "description" field.
func (puo *ProductUpdateOne) SetDescription(s string) *ProductUpdateOne {
	puo.mutation.SetDescription(s)
	return puo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableDescription(s *string) *ProductUpdateOne {
	if s != nil {
		puo.SetDescription(*s)
	}
	return puo
}

// ClearDescription clears the value of the "description" field.
func (puo *ProductUpdateOne) ClearDescription() *ProductUpdateOne {
	puo.mutation.ClearDescription()
	return puo
}

// SetSku sets the "sku" field.
func (puo *ProductUpdateOne) SetSku(s string) *ProductUpdateOne {
	puo.mutation.SetSku(s)
	return puo
}

// SetNillableSku sets the "sku" field if the given value is not nil.
func (puo *ProductUpdateOne) SetNillableSku(s *string) *ProductUpdateOne {
	if s != nil {
		puo.SetSku(*s)
	}
	return puo
}

// ClearSku clears the value of the "sku" field.
func (puo *ProductUpdateOne) ClearSku() *ProductUpdateOne {
	puo.mutation.ClearSku()
	return puo
}

// AddBarcodeIDs adds the "barcodes" edge to the Barcode entity by IDs.
func (puo *ProductUpdateOne) AddBarcodeIDs(ids ...int64) *ProductUpdateOne {
	puo.mutation.AddBarcodeIDs(ids...)
	return puo
}

// AddBarcodes adds the "barcodes" edges to the Barcode entity.
func (puo *ProductUpdateOne) AddBarcodes(b ...*Barcode) *ProductUpdateOne {
	ids := make([]int64, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return puo.AddBarcodeIDs(ids...)
}

// AddPriceHistoryIDs adds the "price_histories" edge to the PriceHistory entity by IDs.
func (puo *ProductUpdateOne) AddPriceHistoryIDs(ids ...int64) *ProductUpdateOne {
	puo.mutation.AddPriceHistoryIDs(ids...)
	return puo
}

// AddPriceHistories adds the "price_histories" edges to the PriceHistory entity.
func (puo *ProductUpdateOne) AddPriceHistories(p ...*PriceHistory) *ProductUpdateOne {
	ids := make([]int64, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return puo.AddPriceHistoryIDs(ids...)
}

// Mutation returns the ProductMutation object of the builder.
func (puo *ProductUpdateOne) Mutation() *ProductMutation {
	return puo.mutation
}

// ClearBarcodes clears all "barcodes" edges to the Barcode entity.
func (puo *ProductUpdateOne) ClearBarcodes() *ProductUpdateOne {
	puo.mutation.ClearBarcodes()
	return puo
}

// RemoveBarcodeIDs removes the "barcodes" edge to Barcode entities by IDs.
func (puo *ProductUpdateOne) RemoveBarcodeIDs(ids ...int64) *ProductUpdateOne {
	puo.mutation.RemoveBarcodeIDs(ids...)
	return puo
}

// RemoveBarcodes removes "barcodes" edges to Barcode entities.
func (puo *ProductUpdateOne) RemoveBarcodes(b ...*Barcode) *ProductUpdateOne {
	ids := make([]int64, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return puo.RemoveBarcodeIDs(ids...)
}

// ClearPriceHistories clears all "price_histories" edges to the PriceHistory entity.
func (puo *ProductUpdateOne) ClearPriceHistories() *ProductUpdateOne {
	puo.mutation.ClearPriceHistories()
	return puo
}

// RemovePriceHistoryIDs removes the "price_histories" edge to PriceHistory entities by IDs.
func (puo *ProductUpdateOne) RemovePriceHistoryIDs(ids ...int64) *ProductUpdateOne {
	puo.mutation.RemovePriceHistoryIDs(ids...)
	return puo
}

// RemovePriceHistories removes "price_histories" edges to PriceHistory entities.
func (puo *ProductUpdateOne) RemovePriceHistories(p ...*PriceHistory) *ProductUpdateOne {
	ids := make([]int64, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return puo.RemovePriceHistoryIDs(ids...)
}

// Where appends a list predicates to the ProductUpdate builder.
func (puo *ProductUpdateOne) Where(ps ...predicate.Product) *ProductUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *ProductUpdateOne) Select(field string, fields ...string) *ProductUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Product entity.
func (puo *ProductUpdateOne) Save(ctx context.Context) (*Product, error) {
	if err := puo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *ProductUpdateOne) SaveX(ctx context.Context) *Product {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *ProductUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *ProductUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (puo *ProductUpdateOne) defaults() error {
	if _, ok := puo.mutation.UpdatedAt(); !ok {
		if product.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized product.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := product.UpdateDefaultUpdatedAt()
		puo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (puo *ProductUpdateOne) check() error {
	if v, ok := puo.mutation.Name(); ok {
		if err := product.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Product.name": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Unit(); ok {
		if err := product.UnitValidator(v); err != nil {
			return &ValidationError{Name: "unit", err: fmt.Errorf(`ent: validator failed for field "Product.unit": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (puo *ProductUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ProductUpdateOne {
	puo.modifiers = append(puo.modifiers, modifiers...)
	return puo
}

func (puo *ProductUpdateOne) sqlSave(ctx context.Context) (_node *Product, err error) {
	if err := puo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(product.Table, product.Columns, sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt64))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Product.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, product.FieldID)
		for _, f := range fields {
			if !product.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != product.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.UpdatedAt(); ok {
		_spec.SetField(product.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := puo.mutation.DeletedAt(); ok {
		_spec.SetField(product.FieldDeletedAt, field.TypeTime, value)
	}
	if puo.mutation.DeletedAtCleared() {
		_spec.ClearField(product.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := puo.mutation.Name(); ok {
		_spec.SetField(product.FieldName, field.TypeString, value)
	}
	if value, ok := puo.mutation.Barcode(); ok {
		_spec.SetField(product.FieldBarcode, field.TypeString, value)
	}
	if puo.mutation.BarcodeCleared() {
		_spec.ClearField(product.FieldBarcode, field.TypeString)
	}
	if value, ok := puo.mutation.CategoryID(); ok {
		_spec.SetField(product.FieldCategoryID, field.TypeInt64, value)
	}
	if value, ok := puo.mutation.AddedCategoryID(); ok {
		_spec.AddField(product.FieldCategoryID, field.TypeInt64, value)
	}
	if puo.mutation.CategoryIDCleared() {
		_spec.ClearField(product.FieldCategoryID, field.TypeInt64)
	}
	if value, ok := puo.mutation.Unit(); ok {
		_spec.SetField(product.FieldUnit, field.TypeEnum, value)
	}
	if value, ok := puo.mutation.PurchasePrice(); ok {
		_spec.SetField(product.FieldPurchasePrice, field.TypeFloat64, value)
	}
	if value, ok := puo.mutation.AddedPurchasePrice(); ok {
		_spec.AddField(product.FieldPurchasePrice, field.TypeFloat64, value)
	}
	if puo.mutation.PurchasePriceCleared() {
		_spec.ClearField(product.FieldPurchasePrice, field.TypeFloat64)
	}
	if value, ok := puo.mutation.SellingPrice(); ok {
		_spec.SetField(product.FieldSellingPrice, field.TypeFloat64, value)
	}
	if value, ok := puo.mutation.AddedSellingPrice(); ok {
		_spec.AddField(product.FieldSellingPrice, field.TypeFloat64, value)
	}
	if puo.mutation.SellingPriceCleared() {
		_spec.ClearField(product.FieldSellingPrice, field.TypeFloat64)
	}
	if value, ok := puo.mutation.Description(); ok {
		_spec.SetField(product.FieldDescription, field.TypeString, value)
	}
	if puo.mutation.DescriptionCleared() {
		_spec.ClearField(product.FieldDescription, field.TypeString)
	}
	if value, ok := puo.mutation.Sku(); ok {
		_spec.SetField(product.FieldSku, field.TypeString, value)
	}
	if puo.mutation.SkuCleared() {
		_spec.ClearField(product.FieldSku, field.TypeString)
	}
	if puo.mutation.BarcodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   product.BarcodesTable,
			Columns: []string{product.BarcodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(barcode.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.RemovedBarcodesIDs(); len(nodes) > 0 && !puo.mutation.BarcodesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   product.BarcodesTable,
			Columns: []string{product.BarcodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(barcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.BarcodesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   product.BarcodesTable,
			Columns: []string{product.BarcodesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(barcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if puo.mutation.PriceHistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   product.PriceHistoriesTable,
			Columns: []string{product.PriceHistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricehistory.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.RemovedPriceHistoriesIDs(); len(nodes) > 0 && !puo.mutation.PriceHistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   product.PriceHistoriesTable,
			Columns: []string{product.PriceHistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricehistory.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.PriceHistoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   product.PriceHistoriesTable,
			Columns: []string{product.PriceHistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricehistory.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(puo.modifiers...)
	_node = &Product{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{product.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
