// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Barcode is the predicate function for barcode builders.
type Barcode func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// PriceHistory is the predicate function for pricehistory builders.
type PriceHistory func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)
